export const ACCOUNT_CREDENTIAL_AUTH_ROUTES = Object.freeze([
  Object.freeze({
    method: 'POST',
    path: '/api/v1/auth/credential-children',
    operationId: 'issueChildWithParentKey',
    rateLimitFamily: null,
    scope: 'product',
    status: 'registered',
    note: 'Raw parent credential; never forwarded through Better Auth',
  }),
  Object.freeze({
    method: 'GET',
    path: '/api/v1/auth/credential-children',
    operationId: 'listChildrenWithParentKey',
    rateLimitFamily: null,
    scope: 'product',
    status: 'registered',
    note: 'Raw parent credential; never forwarded through Better Auth',
  }),
  Object.freeze({
    method: 'GET',
    path: '/api/v1/auth/credential-children/:credentialId',
    operationId: 'getChildWithParentKey',
    rateLimitFamily: null,
    scope: 'product',
    status: 'registered',
    note: 'Raw parent credential; never forwarded through Better Auth',
  }),
  Object.freeze({
    method: 'POST',
    path: '/api/v1/auth/credential-children/:credentialId/rotate',
    operationId: 'rotateChildWithParentKey',
    rateLimitFamily: null,
    scope: 'product',
    status: 'registered',
    note: 'Raw parent credential; never forwarded through Better Auth',
  }),
  Object.freeze({
    method: 'POST',
    path: '/api/v1/auth/credential-children/:credentialId/revoke',
    operationId: 'revokeChildWithParentKey',
    rateLimitFamily: null,
    scope: 'product',
    status: 'registered',
    note: 'Raw parent credential; never forwarded through Better Auth',
  }),
  Object.freeze({
    method: 'POST',
    path: '/api/v1/auth/key-token',
    operationId: 'exchangeAccountKey',
    rateLimitFamily: null,
    scope: 'product',
    status: 'registered',
    note: 'Child credential JSON grant; never forwarded through Better Auth',
  }),
]);
