import { expect, test, type BrowserContext, type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { signInShared } from './auth-bootstrap'
import { enableReaderAcceptance } from './reader-bootstrap'
import { createDeskBookmark, openCollectionEditorAfterDeskCreate, selectCollectionVisibility } from './collection-bootstrap'

const controlUrl = process.env.KNOWN_REAL_STACK_CONTROL_URL
const controlToken = process.env.KNOWN_REAL_STACK_CONTROL_TOKEN
const webBaseUrl = process.env.KNOWN_REAL_STACK_WEB_BASE_URL ?? ''
const apiOrigin = process.env.KNOWN_REAL_STACK_API_ORIGIN
if (!controlUrl || !controlToken || !webBaseUrl || !apiOrigin) throw new Error('Reading Progress real-stack infrastructure is required')
const screenshotDirectory = process.env.KNOWN_REAL_STACK_SCREENSHOT_DIR
  ? resolve(process.env.KNOWN_REAL_STACK_SCREENSHOT_DIR)
  : resolve(process.cwd(), '../../Known-Backend/docs/evidence/screenshots')
async function control<T>(path: string, body?: unknown): Promise<T> { const response = await fetch(`${controlUrl}${path}`, { method: 'POST', headers: { authorization: `Bearer ${controlToken}`, ...(body === undefined ? {} : { 'content-type': 'application/json' }) }, body: body === undefined ? undefined : JSON.stringify(body) }); if (!response.ok) throw new Error(`${path} failed ${response.status}: ${await response.text()}`); return response.json() as Promise<T> }
async function login(page: Page) { await enableReaderAcceptance(page.context()); await signInShared(page) }
async function secondSession(context: BrowserContext, collectionId: string) { await enableReaderAcceptance(context); const session = await control<{ cookieValue: string }>('/reading-progress/second-session', { collectionId }); const url = new URL(webBaseUrl); url.protocol = 'https:'; await context.addCookies([{ name: '__Host-known_session', value: session.cookieValue, url: url.origin, httpOnly: true, secure: true, sameSite: 'Lax' }]) }
async function fixture(page: Page) { await page.getByLabel('Title').fill('Progress acceptance collection'); await page.getByRole('button', { name: 'Create', exact: true }).click(); const collectionId = await openCollectionEditorAfterDeskCreate(page); await createDeskBookmark(page, 'Progress acceptance node', 'https://progress.acceptance.test'); const nodeId = await page.evaluate(async (id) => { const response = await fetch(`/api/v1/collections/${id}/editor?limit=20`); if (!response.ok) throw new Error(`authoritative editor read failed: ${response.status}`); const body = await response.json() as { nodes?: Array<{ id: string; title: string }> }; const node = body.nodes?.find((candidate) => candidate.title === 'Progress acceptance node'); if (!node) throw new Error('created Reading Progress target missing from authoritative editor read'); return node.id }, collectionId); return { collectionId, nodeId } }
async function evidence(page: Page, name: string) { await mkdir(screenshotDirectory, { recursive: true }); await page.emulateMedia({ reducedMotion: 'reduce' }); await page.evaluate(() => document.fonts.ready); await page.screenshot({ path: resolve(screenshotDirectory, name), fullPage: true }) }
function progressPut(page: Page, status: 'in_progress' | 'completed') { return page.waitForResponse((response) => { if (response.request().method() !== 'PUT' || !response.url().includes('/api/v1/reading-progress/')) return false; try { return (response.request().postDataJSON() as { status?: string }).status === status } catch { return false } }) }

test('progress survives refresh/navigation/restart and two Sessions reconcile deterministic stale ETags', async ({ page, browser }) => {
  await login(page); const { collectionId, nodeId } = await fixture(page); await page.goto(`/read/${nodeId}?collectionId=${collectionId}&subjectType=node`)
  await expect(page.getByTestId('reading-progress-state')).toHaveAttribute('data-progress-save-state', 'saved')
  const completed = progressPut(page, 'completed'); await page.getByRole('button', { name: 'Mark complete' }).click(); expect([200, 201]).toContain((await completed).status()); await expect(page.getByTestId('reading-progress-state')).toHaveAttribute('data-progress-save-state', 'saved'); await page.reload(); await expect(page.getByRole('button', { name: /Completed/u })).toBeVisible()
  const second = await browser.newContext(); try { await secondSession(second, collectionId); const other = await second.newPage(); await other.goto(`${webBaseUrl}/read/${nodeId}?collectionId=${collectionId}&subjectType=node`); await expect(other.getByRole('button', { name: /Completed/u })).toBeVisible(); const uncompleted = progressPut(page, 'in_progress'); await page.getByRole('button', { name: /Completed/u }).click(); expect((await uncompleted).status()).toBe(200); await expect(page.getByTestId('reading-progress-state')).toHaveAttribute('data-progress-save-state', 'saved'); const stale = progressPut(other, 'in_progress'); await other.getByRole('button', { name: /Completed/u }).click(); expect((await stale).status()).toBe(412); await expect(other.getByTestId('reading-progress-state')).toHaveAttribute('data-progress-save-state', 'saved'); await expect(other.getByRole('button', { name: 'Mark complete' })).toBeVisible(); await page.reload(); await expect(page.getByTestId('reading-progress-state')).toHaveAttribute('data-progress-save-state', 'saved'); await expect(page.getByRole('button', { name: 'Mark complete' })).toBeVisible() } finally { await second.close() }
  await control('/api-and-worker/restart-and-await', { aggregateId: collectionId }); await page.reload(); await expect(page.getByTestId('reading-progress-state')).toBeVisible(); await page.goto('/library?view=reading'); await expect(page.getByText('Progress acceptance node', { exact: true })).toBeVisible()
  for (const viewport of [{ width: 1280, height: 800 }, { width: 375, height: 720 }]) { await page.setViewportSize(viewport); await expect(page.getByText('Progress acceptance node', { exact: true })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await evidence(page, viewport.width === 1280 ? 'p2b20-reading-progress-desktop.png' : 'p2b20-reading-progress-mobile.png') }
})

test('unknown outcome replays the same command and anonymous Publication never leaks reading state', async ({ page, browser }) => {
  await login(page); const { collectionId, nodeId } = await fixture(page)
  await selectCollectionVisibility(page, 'Public'); await page.getByLabel('Public address').fill(`reading-progress-e2e-${Date.now().toString(36)}`); await page.getByRole('button', { name: 'Save collection', exact: true }).click(); await expect(page.getByText('Collection settings saved').first()).toBeVisible()
  const commands: string[] = []; let dropped = false
  await page.goto(`/read/${nodeId}?collectionId=${collectionId}&subjectType=node`); await expect(page.getByTestId('reading-progress-state')).toHaveAttribute('data-progress-save-state', 'saved'); await expect(page.locator('.reader-article')).toBeVisible(); await expect(page.getByTestId('reading-progress-state')).toHaveAttribute('data-progress-save-state', 'saved')
  await page.route(`**/api/v1/reading-progress/node/${nodeId}`, async (route) => { if (route.request().method() !== 'PUT') return route.continue(); commands.push(route.request().headers()['known-command-id'] ?? ''); if (!dropped) { dropped = true; const committed = await route.fetch(); expect([200, 201]).toContain(committed.status()); await route.abort('connectionreset'); return } await route.continue() })
  await page.getByRole('button', { name: 'Mark complete' }).click(); await expect(page.getByRole('button', { name: 'Retry progress' })).toBeVisible(); await page.getByRole('button', { name: 'Retry progress' }).click(); expect(commands).toHaveLength(2); expect(commands[1]).toBe(commands[0])
  const privateState = await page.evaluate(async (resourceId) => { const [sessionResponse, meResponse, current] = await Promise.all([fetch('/api/v1/session'), fetch('/api/v1/me'), fetch(`/api/v1/reading-progress/node/${resourceId}`)]); const session = await sessionResponse.json() as { csrfToken: string }; const me = await meResponse.json() as { account: { id: string } }; const commandId = crypto.randomUUID(); const response = await fetch(`/api/v1/reading-progress/node/${resourceId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': session.csrfToken, 'Known-Command-Id': commandId, 'If-Match': current.headers.get('etag')! }, body: JSON.stringify({ status: 'in_progress', progress: 0.73124 }) }); if (!response.ok) throw new Error(`private Reading Progress update failed: ${response.status}`); return { accountId: me.account.id, commandId } }, nodeId)
  const anonymous = await browser.newContext(); try { const response = await anonymous.request.get(`${apiOrigin}/colp/v0.1/collections/${collectionId}/snapshot?include=annotations`, { headers: { Accept: 'application/vnd.collection-protocol.snapshot+json;version=0.1', 'Collection-Protocol-Version': '0.1' } }); expect(response.status()).toBe(200); const text = await response.text(); expect(text).not.toContain(privateState.accountId); expect(text).not.toContain(privateState.commandId); expect(text).not.toContain('0.73124'); expect(text).not.toMatch(/reading_state|readingProgress|reading_progress|completedAt/u) } finally { await anonymous.close() }
})
