export {
  ABOUT_MAX,
  ALLOWED_ID_TOKEN_ALGORITHMS,
  BARE_HANDLE_ATTEMPTS,
  HANDLE_ADJECTIVES,
  HANDLE_CLAIM_MAX,
  HANDLE_NOUNS,
  HANDLE_WORD_MAX,
  IdentityError,
  IdTokenVerificationError,
  OIDC_LOGIN_TRANSACTION_TTL_MS,
  SESSION_ABSOLUTE_TTL_MS,
  SESSION_IDLE_TTL_MS,
  SESSION_ROTATION_MIN_AGE_MS,
  SESSION_TOUCH_MIN_INTERVAL_MS,
  assertAccountCanIssueSession,
  assertClaimableHandle,
  assertNonEmpty,
  assertSafeRelativeReturnTo,
  canonicalizeSafeReturnTo,
  assertSameOriginAvatarUrl,
  assertSessionUsable,
  assertValidAbout,
  assertValidAvatarUrl,
  assertValidDisplayName,
  assertValidEmail,
  assertValidHandle,
  isValidAvatarUrl,
  DEFAULT_OIDC_EMAIL_TRUST_POLICY,
  NOOP_OIDC_CLAIM_SYNC_METRICS,
  OIDC_AVATAR_URL_REJECTED_METRIC,
  resolveTrustedOidcClaims,
  computeSessionExpiryWindow,
  computeSlidIdleExpiry,
  createIdTokenVerifier,
  createOidcTransactionSecrets,
  createSessionRotationSecrets,
  createTestOidcTransactionSecrets,
  createTestSessionRotationSecrets,
  deriveCsrfTokenRaw,
  encodeOidcEncryptionKeyBase64,
  generateAutomaticHandle,
  generateCsrfTokenRaw,
  generateOidcStateMaterial,
  generateOpaqueId,
  generatePkceCodeVerifier,
  generateSessionTokenRaw,
  hashSecret,
  hashesMatch,
  isProtectedOidcTransaction,
  isSafeRelativeReturnTo,
  isSecurityEpochMatch,
  isSessionAbsoluteExpired,
  isSessionExpired,
  isSessionIdleExpired,
  isSessionRevoked,
  materializeOidcLoginTransactionForUse,
  parseOidcEncryptionKeysEnv,
  secretsMatch,
  shouldRotateSession,
  shouldTouchSession,
  OIDC_NONCE_DIGEST_PURPOSE,
  OIDC_STATE_DIGEST_PURPOSE,
  type Account,
  type AccountIdentity,
  type AccountStatus,
  type AccountWithProfile,
  type AllowedIdTokenAlgorithm,
  type AuthUserAccountMapping,
  type IdentityErrorCode,
  type IdTokenVerificationFailureReason,
  type IdTokenVerifier,
  type IdTokenVerifierOptions,
  type IdTokenVerifyInput,
  type IssuedSessionSecrets,
  type JwksProvider,
  type MappedBusinessAccount,
  type OidcClaimSyncMetrics,
  type OidcEmailTrustPolicy,
  type OidcEncryptionKey,
  type OidcLoginTransaction,
  type OidcTransactionSecretsConfig,
  type OidcTransactionSecretsPort,
  type PkceEncryptionResult,
  type Profile,
  type ProfileHandle,
  type ResolveTrustedOidcClaimsInput,
  type Session,
  type SessionExpiryWindow,
  type SessionRotationSecretsPort,
  type TrustedOidcProfileClaims,
  type VerifiedIdTokenClaims,
} from './domain/index.js';

export {
  authenticateSession,
  bootstrapBrowserSession,
  bumpAccountSecurityEpoch,
  claimHandle,
  claimOrReleaseHandle,
  consumeOidcLoginTransaction,
  createIdentityApplication,
  createOidcLoginTransaction,
  createSession,
  ensureAccountFromOidcIdentity,
  ensureAccountHandle,
  getAccountWithProfile,
  getAccountWithProfileBySubjectId,
  releaseHandle,
  revokeSession,
  rotateSession,
  touchSession,
  updateProfileSettings,
  updateProfileSettingsWithReceipt,
  profileSettingsCommandFingerprint,
  PROFILE_SETTINGS_COMMAND_ROUTE,
  PROFILE_SETTINGS_COMMAND_SCOPE,
  PROFILE_SETTINGS_CONTRACT_VERSION,
  BOOKMARK_PREFERENCES_CONTRACT_VERSION,
  BOOKMARK_PREFERENCES_ROUTE,
  BookmarkPreferencesError,
  BookmarkPreferencesPreconditionError,
  getBookmarkPreferences,
  parseBookmarkPreferencesPatch,
  updateBookmarkPreferences,
  virtualBookmarkPreferences,
  type AccountIdentityRepository,
  type AccountRepository,
  type AuthenticateSessionOptions,
  type AuthenticatedSession,
  type BootstrapBrowserSessionOptions,
  type BootstrappedBrowserSession,
  type ClaimHandleInput,
  type CreateOidcLoginTransactionInput,
  type CreateOidcLoginTransactionResult,
  type CreateSessionInput,
  type EnsureAccountFromOidcInput,
  type IdentityApplication,
  type IdentityClock,
  type IdentityPorts,
  type IdentityUnitOfWork,
  type OidcLoginTransactionRepository,
  type PendingUnboundInvitePurgePort,
  type ProfileHandleRepository,
  type ProfileRepository,
  type PublicProfileFacts,
  type PublicProfileFactsReadPort,
  type PublicProfileOwnerFactsReadPort,
  type RotateSessionOptions,
  type SessionRepository,
  type ProfileSettingsCommandBody,
  type UpdateProfileSettingsCommandInput,
  type UpdateProfileSettingsCommandResult,
  type UpdateProfileSettingsInput,
  type BookmarkInsertPosition,
  type BookmarkPreferencesPatch,
  type BookmarkPreferencesPorts,
  type BookmarkPreferencesStore,
  type BookmarkPreferencesView,
  type UpdateBookmarkPreferencesResult,
  type VerifiedAccountEmailPort,
  type VerifiedActiveAccountByEmail,
  ensureExtensionAccountIdentity,
  type EnsureExtensionAccountIdentityInput,
  type EnsureExtensionAccountIdentityOptions,
  EXPLORE_UNKNOWN_CREATOR_ID,
  type ExploreCreatorFacts,
  type ExploreCreatorsQueryPort,
  assertAvatarImage,
  assertAvatarPrefixesDoNotOverlap,
  avatarUploadBodyFingerprint,
  readAvatarBodyCapped,
  AVATAR_READ_TIMEOUT_MS,
  uploadAvatar,
  prepareAvatarUpload,
  AVATAR_ALLOWED_CONTENT_TYPES,
  AVATAR_MAX_BYTES,
  type AvatarObjectStore,
  type StoredAvatar,
  type UploadAvatarInput,
  type UploadAvatarResult,
} from './application/index.js';
export { getPublicProfileFacts, isCanonicalPublicProfileHandle } from './application/index.js';

export {
  EXTENSION_AUTH_ALLOWED_ALGORITHMS,
  EXTENSION_AUTH_FLOW,
  ExtensionAuthError,
  createExtensionCredentialEvidenceVerifier,
  createCompositeExtensionCredentialVerifier,
  createSessionBackedExtensionCredentialVerifier,
  isJoseCompactToken,
  isVerifiedExtensionCredential,
  createPkceAuthorizationFlow,
  parseExtensionAuthConfig,
  parseSingleBearerAuthorization,
  verifyPkceIdToken,
  type ExtensionAuthAlgorithm,
  type ExtensionAuthConfig,
  type ExtensionAuthFailureReason,
  type ExtensionBrowserSessionPort,
  type ExtensionCredentialEvidencePort,
  type ExtensionCredentialEvidenceVerifierOptions,
  type ExtensionIdentityBinding,
  type ExtensionIdentityBindingPort,
  type ExtensionOwnerSubjectPort,
  type ExtensionJwksProvider,
  type ExtensionSessionActor,
  type SessionBackedExtensionCredentialVerifierOptions,
  type PkceAuthorizationCompletion,
  type PkceAuthorizationFlow,
  type PkceAuthorizationStart,
  type VerifiedExtensionCredential,
  type VerifiedPkceIdToken,
} from './extension-auth.js';
export {
  CLASSIFICATION_CREDIT_PRICE, MAX_CREDIT_POINTS, CreditError, checkClassificationCreditConsent,
  type CreditFailureCode, type CreditQuoteContext, type CreditReservation, type CreditBalanceFacts,
  type CreditReconciliation, type CreditReleaseReason, type CreditChargeTotals, type AccountCreditsPort,
} from './application/credits.js';
export type {
  CreditLedgerBalanceFacts, CreditLedgerEntryBalanceFacts, CreditLedgerEntryFacts, CreditLedgerFilters, CreditLedgerKind,
  CreditLedgerReadPageFacts, CreditLedgerReadPort, CreditLedgerSnapshotFacts, CreditLedgerSource,
  CreditLedgerTaskFacts,
} from './application/credit-ledger-read.js';
export {
  CREDIT_LEDGER_CURSOR_PURPOSE, CREDIT_LEDGER_CURSOR_TTL_MS,
  createCreditLedgerCursorCodec,
} from './application/credit-ledger-cursor.js';
export type {
  CreditLedgerCursorBalance, CreditLedgerCursorKeyConfig, CreditLedgerCursorPayload,
} from './application/credit-ledger-cursor.js';
