import { sql, type Kysely, type Migration } from 'kysely';

/**
 * T-02 expand: Better Auth 1.7.1 `auth_accounts.issuer` + oauth-provider tables.
 *
 * Transcribed from T-01 `getMigrations().compileMigrations()`
 * (`Known-Backend/scripts/t01-better-auth-1-7-compile-migrations.mts`,
 * artifacts `oauth-mapped-after-kysely.sql` / `compile-review.json`).
 * Not generated by Better Auth CLI.
 *
 * `issuer` is added nullable, backfilled, then NOT NULL + unique
 * `(issuer, accountId)`. Existing rows would fail a bare ADD NOT NULL.
 *
 * Backfill (Better Auth 1.7 upgrade guide + Know-N social providers):
 * - credential → `local:credential`
 * - siwe → `local:siwe`
 * - google → `https://accounts.google.com` (BA 1.7 `accountIssuer`)
 * - other OAuth → `local:oauth:` + encodeURIComponent(providerId)
 * Non-null issuer values are left untouched.
 *
 * New tables use `auth_oauth_*` / `auth_jwks` modelNames (ADR P2).
 * Expand-only: production does not run down.
 */
export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`ALTER TABLE "auth_accounts" ADD COLUMN "issuer" text`.execute(db);

  await sql`
    CREATE OR REPLACE FUNCTION pg_temp.ba17_encode_uri_component(input text) RETURNS text
    LANGUAGE plpgsql IMMUTABLE STRICT AS $fn$
    DECLARE
      result text := '';
      i int;
      ch text;
      bytes bytea;
      b int;
    BEGIN
      FOR i IN 1..char_length(input) LOOP
        ch := substr(input, i, 1);
        IF ch ~ '[A-Za-z0-9_.!~*''()-]' THEN
          result := result || ch;
        ELSE
          bytes := convert_to(ch, 'UTF8');
          FOR b IN 0 .. octet_length(bytes) - 1 LOOP
            result := result || '%' || upper(lpad(to_hex(get_byte(bytes, b)), 2, '0'));
          END LOOP;
        END IF;
      END LOOP;
      RETURN result;
    END
    $fn$
  `.execute(db);

  await sql`
    UPDATE "auth_accounts"
       SET issuer = CASE
         WHEN "providerId" = 'credential' THEN 'local:credential'
         WHEN "providerId" = 'siwe' THEN 'local:siwe'
         WHEN "providerId" = 'google' THEN 'https://accounts.google.com'
         ELSE 'local:oauth:' || pg_temp.ba17_encode_uri_component("providerId")
       END
     WHERE issuer IS NULL
  `.execute(db);
  await sql`DROP FUNCTION IF EXISTS pg_temp.ba17_encode_uri_component(text)`.execute(db);

  await sql`DO $guard$
    DECLARE
      unresolved bigint;
      collisions bigint;
    BEGIN
      SELECT count(*) INTO unresolved FROM "auth_accounts" WHERE issuer IS NULL;
      IF unresolved > 0 THEN
        RAISE EXCEPTION 'better_auth_oauth_provider_schema issuer backfill refused: % auth_accounts row(s) still have NULL issuer',
          unresolved;
      END IF;
      SELECT count(*) INTO collisions FROM (
        SELECT 1 FROM "auth_accounts" GROUP BY issuer, "accountId" HAVING count(*) > 1
      ) dupes;
      IF collisions > 0 THEN
        RAISE EXCEPTION 'better_auth_oauth_provider_schema issuer backfill refused: % duplicate (issuer, accountId) group(s)',
          collisions;
      END IF;
    END
  $guard$`.execute(db);

  await sql`ALTER TABLE "auth_accounts" ALTER COLUMN "issuer" SET NOT NULL`.execute(db);
  await sql`CREATE UNIQUE INDEX "auth_accounts_issuer_accountId_uidx"
    ON "auth_accounts" ("issuer", "accountId")`.execute(db);

  await sql`CREATE TABLE "auth_jwks" (
    "id" text PRIMARY KEY,
    "publicKey" text NOT NULL,
    "privateKey" text NOT NULL,
    "createdAt" timestamptz NOT NULL,
    "expiresAt" timestamptz,
    "alg" text,
    "crv" text
  )`.execute(db);

  await sql`CREATE TABLE "auth_oauth_client" (
    "id" text PRIMARY KEY,
    "clientId" text NOT NULL UNIQUE,
    "clientSecret" text,
    "clientDiscoveryId" text,
    "disabled" boolean,
    "skipConsent" boolean,
    "enableEndSession" boolean,
    "subjectType" text,
    "scopes" jsonb,
    "clientCredentialsScopes" jsonb,
    "userId" text REFERENCES "auth_users" ("id") ON DELETE CASCADE,
    "createdAt" timestamptz,
    "updatedAt" timestamptz,
    "name" text,
    "uri" text,
    "icon" text,
    "contacts" jsonb,
    "tos" text,
    "policy" text,
    "softwareId" text,
    "softwareVersion" text,
    "softwareStatement" text,
    "redirectUris" jsonb NOT NULL,
    "postLogoutRedirectUris" jsonb,
    "backchannelLogoutUri" text,
    "backchannelLogoutSessionRequired" boolean,
    "tokenEndpointAuthMethod" text,
    "applicationType" text,
    "jwks" text,
    "jwksUri" text,
    "grantTypes" jsonb,
    "responseTypes" jsonb,
    "requirePKCE" boolean,
    "dpopBoundAccessTokens" boolean,
    "referenceId" text,
    "metadata" jsonb
  )`.execute(db);

  await sql`CREATE TABLE "auth_oauth_resource" (
    "id" text PRIMARY KEY,
    "identifier" text NOT NULL UNIQUE,
    "name" text NOT NULL,
    "accessTokenTtl" integer,
    "refreshTokenTtl" integer,
    "signingAlgorithm" text,
    "signingKeyId" text,
    "allowedScopes" jsonb,
    "customClaims" jsonb,
    "dpopBoundAccessTokensRequired" boolean,
    "disabled" boolean,
    "createdAt" timestamptz,
    "updatedAt" timestamptz,
    "policyVersion" integer,
    "metadata" jsonb
  )`.execute(db);

  await sql`CREATE TABLE "auth_oauth_client_resource" (
    "id" text PRIMARY KEY,
    "clientId" text NOT NULL REFERENCES "auth_oauth_client" ("clientId") ON DELETE CASCADE,
    "resourceId" text NOT NULL REFERENCES "auth_oauth_resource" ("identifier") ON DELETE CASCADE,
    "metadata" jsonb,
    "createdAt" timestamptz
  )`.execute(db);

  await sql`CREATE TABLE "auth_oauth_refresh_token" (
    "id" text PRIMARY KEY,
    "token" text NOT NULL UNIQUE,
    "clientId" text NOT NULL REFERENCES "auth_oauth_client" ("clientId") ON DELETE CASCADE,
    "sessionId" text REFERENCES "auth_sessions" ("id") ON DELETE SET NULL,
    "userId" text NOT NULL REFERENCES "auth_users" ("id") ON DELETE CASCADE,
    "referenceId" text,
    "authorizationCodeId" text,
    "resources" jsonb,
    "requestedUserInfoClaims" jsonb,
    "expiresAt" timestamptz NOT NULL,
    "createdAt" timestamptz NOT NULL,
    "revoked" timestamptz,
    "rotatedAt" timestamptz,
    "rotationReplayResponse" text,
    "rotationReplayExpiresAt" timestamptz,
    "authTime" timestamptz,
    "confirmation" jsonb,
    "scopes" jsonb NOT NULL
  )`.execute(db);

  await sql`CREATE TABLE "auth_oauth_access_token" (
    "id" text PRIMARY KEY,
    "token" text NOT NULL UNIQUE,
    "clientId" text NOT NULL REFERENCES "auth_oauth_client" ("clientId") ON DELETE CASCADE,
    "sessionId" text REFERENCES "auth_sessions" ("id") ON DELETE SET NULL,
    "userId" text REFERENCES "auth_users" ("id") ON DELETE CASCADE,
    "referenceId" text,
    "authorizationCodeId" text,
    "resources" jsonb,
    "requestedUserInfoClaims" jsonb,
    "refreshId" text REFERENCES "auth_oauth_refresh_token" ("id") ON DELETE CASCADE,
    "expiresAt" timestamptz NOT NULL,
    "createdAt" timestamptz NOT NULL,
    "revoked" timestamptz,
    "confirmation" jsonb,
    "scopes" jsonb NOT NULL
  )`.execute(db);

  await sql`CREATE TABLE "auth_oauth_consent" (
    "id" text PRIMARY KEY,
    "clientId" text NOT NULL REFERENCES "auth_oauth_client" ("clientId") ON DELETE CASCADE,
    "userId" text REFERENCES "auth_users" ("id") ON DELETE CASCADE,
    "referenceId" text,
    "resources" jsonb,
    "requestedUserInfoClaims" jsonb,
    "scopes" jsonb NOT NULL,
    "createdAt" timestamptz NOT NULL,
    "updatedAt" timestamptz NOT NULL
  )`.execute(db);

  await sql`CREATE TABLE "auth_oauth_client_assertion" (
    "id" text PRIMARY KEY,
    "expiresAt" timestamptz NOT NULL
  )`.execute(db);

  await sql`CREATE INDEX "auth_oauth_client_userId_idx" ON "auth_oauth_client" ("userId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_client_resource_clientId_idx" ON "auth_oauth_client_resource" ("clientId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_client_resource_resourceId_idx" ON "auth_oauth_client_resource" ("resourceId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_refresh_token_clientId_idx" ON "auth_oauth_refresh_token" ("clientId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_refresh_token_sessionId_idx" ON "auth_oauth_refresh_token" ("sessionId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_refresh_token_userId_idx" ON "auth_oauth_refresh_token" ("userId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_refresh_token_authorizationCodeId_idx" ON "auth_oauth_refresh_token" ("authorizationCodeId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_access_token_clientId_idx" ON "auth_oauth_access_token" ("clientId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_access_token_sessionId_idx" ON "auth_oauth_access_token" ("sessionId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_access_token_userId_idx" ON "auth_oauth_access_token" ("userId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_access_token_authorizationCodeId_idx" ON "auth_oauth_access_token" ("authorizationCodeId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_access_token_refreshId_idx" ON "auth_oauth_access_token" ("refreshId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_consent_clientId_idx" ON "auth_oauth_consent" ("clientId")`.execute(db);
  await sql`CREATE INDEX "auth_oauth_consent_userId_idx" ON "auth_oauth_consent" ("userId")`.execute(db);
  await sql`CREATE UNIQUE INDEX "auth_oauth_client_resource_clientId_resourceId_uidx"
    ON "auth_oauth_client_resource" ("clientId", "resourceId")`.execute(db);

  await sql`COMMENT ON TABLE "auth_jwks" IS
    'Better Auth 1.7.1 jwt() JWKS rows (library schema transcription; T-02).'`.execute(db);
  await sql`COMMENT ON TABLE "auth_oauth_client" IS
    'Better Auth 1.7.1 oauth-provider client rows (auth_oauth_* modelName; T-02).'`.execute(db);
  await sql`COMMENT ON COLUMN "auth_accounts"."issuer" IS
    'Better Auth 1.7.1 account identity issuer; backfilled then NOT NULL (T-02).'`.execute(db);
}

/**
 * Developer-only destructive rollback. Refuses while any oauth/jwks table has
 * rows and reports per-table counts. Empty oauth tables may drop even when
 * `auth_accounts` still has rows (issuer column is additive). Production
 * rollback keeps the expand schema installed.
 */
export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`DO $guard$
    DECLARE
      jwks_count bigint;
      client_count bigint;
      resource_count bigint;
      client_resource_count bigint;
      refresh_count bigint;
      access_count bigint;
      consent_count bigint;
      assertion_count bigint;
    BEGIN
      SELECT count(*) INTO jwks_count FROM "auth_jwks";
      SELECT count(*) INTO client_count FROM "auth_oauth_client";
      SELECT count(*) INTO resource_count FROM "auth_oauth_resource";
      SELECT count(*) INTO client_resource_count FROM "auth_oauth_client_resource";
      SELECT count(*) INTO refresh_count FROM "auth_oauth_refresh_token";
      SELECT count(*) INTO access_count FROM "auth_oauth_access_token";
      SELECT count(*) INTO consent_count FROM "auth_oauth_consent";
      SELECT count(*) INTO assertion_count FROM "auth_oauth_client_assertion";
      IF jwks_count + client_count + resource_count + client_resource_count
         + refresh_count + access_count + consent_count + assertion_count > 0 THEN
        RAISE EXCEPTION 'better_auth_oauth_provider_schema down refused: rows remain (auth_jwks=%, auth_oauth_client=%, auth_oauth_resource=%, auth_oauth_client_resource=%, auth_oauth_refresh_token=%, auth_oauth_access_token=%, auth_oauth_consent=%, auth_oauth_client_assertion=%); production rollback keeps the expand schema installed and down is a developer-only zero-row boundary.',
          jwks_count, client_count, resource_count, client_resource_count,
          refresh_count, access_count, consent_count, assertion_count;
      END IF;
    END
  $guard$`.execute(db);

  await sql`DROP TABLE IF EXISTS "auth_oauth_access_token"`.execute(db);
  await sql`DROP TABLE IF EXISTS "auth_oauth_refresh_token"`.execute(db);
  await sql`DROP TABLE IF EXISTS "auth_oauth_consent"`.execute(db);
  await sql`DROP TABLE IF EXISTS "auth_oauth_client_assertion"`.execute(db);
  await sql`DROP TABLE IF EXISTS "auth_oauth_client_resource"`.execute(db);
  await sql`DROP TABLE IF EXISTS "auth_oauth_client"`.execute(db);
  await sql`DROP TABLE IF EXISTS "auth_oauth_resource"`.execute(db);
  await sql`DROP TABLE IF EXISTS "auth_jwks"`.execute(db);
  await sql`DROP INDEX IF EXISTS "auth_accounts_issuer_accountId_uidx"`.execute(db);
  await sql`ALTER TABLE "auth_accounts" DROP COLUMN IF EXISTS "issuer"`.execute(db);
}

export const migration: Migration = { up, down };
export default migration;
