/* eslint-disable */
/**
 * Generated from The Collection Protocol schema.
 * Run `npm run refresh:protocol`; do not edit this file manually.
 */

import type { StrictFeedEvent, StrictFeedNode, StrictNode, StrictNodeCreate, StrictOperation, StrictOperationResult, StrictSnapshotNode } from './strict.js';
export type AbsoluteUri = string;
export type PrincipalId = string;
export type ScopeName =
  | 'collections:list'
  | 'collections:read'
  | 'nodes:read'
  | 'annotations:read'
  | 'attachments:read'
  | 'relations:read'
  | 'source_refs:read'
  | 'feed:read'
  | 'audit:read'
  | 'collections:create'
  | 'collections:write'
  | 'collections:delete'
  | 'nodes:write'
  | 'nodes:delete'
  | 'annotations:write'
  | 'attachments:write'
  | 'relations:write'
  | 'release:publish'
  | 'sync:bootstrap'
  | 'sync:pull'
  | 'sync:push'
  | 'sync:resolve'
  | 'access:read'
  | 'access:write'
  | 'keys:read'
  | 'keys:write'
  | 'rate_limits:read'
  | 'rate_limits:write'
  | 'server:admin';
export type Visibility = 'public' | 'unlisted' | 'protected' | 'private';
export type OpaqueId = string;
export type ActiveReplicaLease = ReplicaLease & {
  state: 'active';
  [k: string]: unknown;
};
export type DateTime = string;
export type HttpUrl = AbsoluteUri & {
  [k: string]: unknown;
};
export type Annotation = {
  [k: string]: unknown;
} & {
  id: OpaqueId;
  collectionId: OpaqueId;
  subject: Subject;
  type: 'note' | 'summary' | 'tldr' | 'highlight' | 'reading_state' | 'rating' | 'custom';
  format?: 'plain' | 'markdown' | 'html' | 'json';
  value: unknown;
  visibility: Visibility;
  creator?: Actor;
  createdAt: DateTime;
  updatedAt: DateTime;
  revision: OpaqueId;
  provenance?: Provenance;
  extensions?: Extensions;
};
export type Provenance = {
  [k: string]: unknown;
} & {
  kind: 'human' | 'ai' | 'imported' | 'derived';
  provider?: string;
  model?: string;
  generatedAt?: DateTime;
  editedByHuman?: boolean;
  sourceNodeIds?: OpaqueId[];
};
export type AnnotationCreate = {
  [k: string]: unknown;
} & {
  subject: Subject;
  type: 'note' | 'summary' | 'tldr' | 'highlight' | 'reading_state' | 'rating' | 'custom';
  format?: 'plain' | 'markdown' | 'html' | 'json';
  value: unknown;
  visibility: Visibility;
  creator?: Actor;
  provenance?: Provenance;
  extensions?: Extensions;
};
export type BookmarkUrl = string;
export type CanonicalResourceUri = string;
export type OperationResult = StrictOperationResult;
export type ChangePlan = {
  [k: string]: unknown;
} & {
  planId: OpaqueId;
  expiresAt: DateTime;
  risk: 'low' | 'medium' | 'high';
  requiresApproval: boolean;
  approvalMethod?: string;
  approvalUri?: HttpUrl;
  summary: string;
  impact: ChangePlanImpact;
  requiredScopes: ScopeName[];
  baseRevisions: {
    [k: string]: OpaqueId;
  };
};
export type ChangePlanOperation =
  | DeleteCollectionPlanOperation
  | DeleteSubtreePlanOperation
  | SetVisibilityPlanOperation
  | SetAccessPolicyPlanOperation
  | CreateKeyPlanOperation
  | RotateKeyPlanOperation
  | RevokeKeyPlanOperation
  | SetRateLimitPlanOperation
  | PublishReleasePlanOperation
  | SyncMirrorPlanOperation;
export type Node = StrictNode;
export type OrderKey = string;
export type FolderRole =
  | 'root'
  | 'bookmarks-bar'
  | 'other-bookmarks'
  | 'mobile-bookmarks'
  | 'managed-bookmarks'
  | 'archive'
  | 'inbox'
  | 'recovered'
  | 'custom';
/**
 * SHA-256 over the exact UTF-8 octets of the preserved bookmark url; a matching value is only a deduplication candidate signal and is never an object ID.
 */
export type UrlHash = string;
export type NodeVisibility = 'inherit' | 'protected' | 'private';
export type ConflictResolutionRequest = {
  [k: string]: unknown;
} & {
  resolution: 'server' | 'incoming' | 'custom' | 'both';
  value?: unknown;
  baseConflictRevision: OpaqueId;
};
export type Operation = StrictOperation;
export type NodeCreate = StrictNodeCreate;
export type FeedEvent = StrictFeedEvent;
export type HttpsUrl = HttpUrl & {
  [k: string]: unknown;
};
export type FeedEventData =
  | CollectionFeedEventData
  | ReleasePublishedFeedEventData
  | NodeChangedFeedEventData
  | NodeDeletedFeedEventData
  | AccessPublicationChangedFeedEventData
  | ExtensionFeedEventData;
export type FeedNode = StrictFeedNode;
export type GlobalResourceType =
  'collection' | 'node' | 'annotation' | 'attachment' | 'relation' | 'operation' | 'event';
/**
 * A bare opaqueId is local and requires an enclosing same-server resourceType context; a cross-server reference is a canonicalResourceUri.
 */
export type GlobalResourceReference = OpaqueId | CanonicalResourceUri;
export type HttpsUriTemplate = {
  [k: string]: unknown;
};
export type HttpsUriTemplate1 = string;
export type LoopbackHttpUrl = HttpUrl & {
  [k: string]: unknown;
};
export type ServiceUrl = HttpsUrl | LoopbackHttpUrl;
export type ManifestMount = {
  [k: string]: unknown;
} & {
  id: OpaqueId;
  baseUrl: ServiceUrl & {
    [k: string]: unknown;
  };
  /**
   * @minItems 1
   */
  profiles: [ProfileName, ...ProfileName[]];
  endpoints: ManifestEndpoints;
  features: ManifestFeatures;
  auth: ManifestAuth;
  limits: ManifestLimits;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^https://[A-Za-z0-9.-]+(?:/[A-Za-z0-9._~!$&'()*+,;=:@%/-]*)?$".
   */
  [k: string]: unknown;
};
export type ProfileName =
  'core' | 'publication' | 'feed' | 'publisher' | 'sync' | 'mcp-read' | 'mcp-write';
export type ManifestAuth = {
  [k: string]: unknown;
} & {
  anonymousRead: boolean;
  apiKeys: boolean;
  oauth: boolean;
  protectedResourceMetadata?: ServiceUrl;
};
export type ManifestSigning = {
  [k: string]: unknown;
} & {
  httpMessageSignatures: boolean;
  jwksUrl?: ServiceUrl;
};
export type Replica = {
  [k: string]: unknown;
} & {
  replicaId: OpaqueId;
  name: string;
  kind: 'browser_extension' | 'desktop_client' | 'mobile_client' | 'server' | 'importer' | 'other';
  adapter: ReplicaAdapter;
  capabilities: ReplicaCapabilities;
  binding?: ReplicaBinding;
  extensions?: Extensions;
};
export type ReplicaBinding = {
  [k: string]: unknown;
} & {
  browserProfileId: OpaqueId;
  mountMode: 'whole-profile' | 'mounted-folder';
  mountNativeId: string | null;
  generation: OpaqueId;
};
export type Snapshot = {
  [k: string]: unknown;
} & {
  protocolVersion: '0.1';
  snapshotId: OpaqueId;
  mode: 'publication' | 'sync';
  complete: boolean;
  collection: Collection;
  nodes: SnapshotNode[];
  annotations: Annotation[];
  attachments: Attachment[];
  relations: Relation[];
  tombstones: SyncTombstone[];
  revision: OpaqueId;
  syncCursor?: OpaqueId;
  recoveryCapability?: OpaqueId;
  generatedAt: DateTime;
  contentDigest?: string;
  page: SnapshotPage;
  warnings: Warning[];
};
export type SnapshotNode = StrictSnapshotNode;
export type SnapshotPage = {
  [k: string]: unknown;
} & {
  nextCursor: null | OpaqueId;
  hasMore: boolean;
  sequence: number;
};
export type SyncPullEvent = {
  [k: string]: unknown;
} & {
  cursor: OpaqueId;
  kind: 'operation' | 'conflict';
  operation?: Operation;
  conflict?: Conflict;
};
export type SyncPush = SyncCollectionPush | SyncInstanceCreatePush;
export type SyncSessionRequest = SyncCollectionSessionRequest | SyncInstanceSessionRequest;
export type SyncSessionResult = SyncCollectionSessionResult | SyncInstanceSessionResult;

export interface ColpContracts {
  absoluteUri: AbsoluteUri;
  accessEntry: AccessEntry;
  accessPolicy: AccessPolicy;
  accessPolicyPatch: AccessPolicyPatch;
  accessPublicationChangedFeedEventData: AccessPublicationChangedFeedEventData;
  accessPublicationPolicy: AccessPublicationPolicy;
  activeReplicaLease: ActiveReplicaLease;
  actor: Actor;
  annotation: Annotation;
  annotationCreate: AnnotationCreate;
  annotationMergePatch: AnnotationMergePatch;
  annotationUpdateOperationPayload: AnnotationUpdateOperationPayload;
  apiKeyCreateRequest: ApiKeyCreateRequest;
  apiKeyCreateResult: ApiKeyCreateResult;
  apiKeyDirectory: ApiKeyDirectory;
  apiKeyMetadata: ApiKeyMetadata;
  apiKeyRevokeResult: ApiKeyRevokeResult;
  apiKeyRotateRequest: ApiKeyRotateRequest;
  apiKeyRotateResult: ApiKeyCreateResult;
  attachment: Attachment;
  attachmentCreate: AttachmentCreate;
  attachmentMergePatch: AttachmentMergePatch;
  attachmentUpdateOperationPayload: AttachmentUpdateOperationPayload;
  auditActor: AuditActor;
  auditConfirmation: AuditConfirmation;
  auditDirectory: AuditDirectory;
  auditEvent: AuditEvent;
  auditQuery: AuditQuery;
  bookmarkUrl: BookmarkUrl;
  canonicalResourceUri: CanonicalResourceUri;
  changeCommitRequest: ChangeCommitRequest;
  changeCommitResult: ChangeCommitResult;
  changeCounts: ChangeCounts;
  changePlan: ChangePlan;
  changePlanImpact: ChangePlanImpact;
  changePlanOperation: ChangePlanOperation;
  changePlanRequest: ChangePlanRequest;
  collection: Collection;
  collectionCreate: CollectionCreate;
  collectionCreateRequest: CreateCollectionOperationPayload;
  collectionCreateResult: CollectionCreateResult;
  collectionDirectory: CollectionDirectory;
  collectionFeedEventData: CollectionFeedEventData;
  collectionLinks: CollectionLinks;
  collectionMergePatch: CollectionMergePatch;
  collectionMetadata: CollectionMetadata;
  collectionMetadataUpdateOperationPayload: CollectionMetadataUpdateOperationPayload;
  conflict: Conflict;
  conflictResolutionRequest: ConflictResolutionRequest;
  conflictResolutionResult: ConflictResolutionResult;
  conversionPolicy: ConversionPolicy;
  conversionPreview: ConversionPreview;
  createAnnotationOperationPayload: CreateAnnotationOperationPayload;
  createAttachmentOperationPayload: CreateAttachmentOperationPayload;
  createCollectionOperationPayload: CreateCollectionOperationPayload;
  createKeyPlanOperation: CreateKeyPlanOperation;
  createNodeOperationPayload: CreateNodeOperationPayload;
  createRelationOperationPayload: CreateRelationOperationPayload;
  cursorPageQuery: CursorPageQuery;
  dateTime: DateTime;
  deleteCollectionPlanOperation: DeleteCollectionPlanOperation;
  deleteOperationPayload: DeleteOperationPayload;
  deleteResult: DeleteResult;
  deleteSubtreePlanOperation: DeleteSubtreePlanOperation;
  deletionReceipt: DeletionReceipt;
  directoryCollection: DirectoryCollection;
  directoryQuery: DirectoryQuery;
  extensionFeedEventData: ExtensionFeedEventData;
  extensions: Extensions;
  feed: Feed;
  feedEvent: FeedEvent;
  feedEventData: FeedEventData;
  feedNode: FeedNode;
  feedQuery: FeedQuery;
  folderRole: FolderRole;
  formattedText: FormattedText;
  globalResourceIdentity: GlobalResourceIdentity;
  globalResourceReference: GlobalResourceReference;
  globalResourceType: GlobalResourceType;
  highlightValue: HighlightValue;
  httpUrl: HttpUrl;
  httpsUriTemplate: HttpsUriTemplate & HttpsUriTemplate1;
  httpsUrl: HttpsUrl;
  loopbackHttpUrl: LoopbackHttpUrl;
  manifest: Manifest;
  manifestAuth: ManifestAuth;
  manifestEndpoints: ManifestEndpoints;
  manifestFeatures: ManifestFeatures;
  manifestLimits: ManifestLimits;
  manifestMount: ManifestMount;
  manifestSigning: ManifestSigning;
  mcpTool: McpTool;
  mcpToolsList: McpToolsList;
  media: Media;
  moveOperationPayload: MoveOperationPayload;
  node: Node;
  nodeChangedFeedEventData: NodeChangedFeedEventData;
  nodeConstraints: NodeConstraints;
  nodeContentUpdateOperationPayload: NodeContentUpdateOperationPayload;
  nodeCreate: NodeCreate;
  nodeCreateRequest: CreateNodeOperationPayload;
  nodeDeleteQuery: NodeDeleteQuery;
  nodeDeletedFeedEventData: NodeDeletedFeedEventData;
  nodeDetail: NodeDetail;
  nodeDetailQuery: NodeDetailQuery;
  nodeIncluded: NodeIncluded;
  nodeMergePatch: NodeMergePatch;
  nodeMoveRequest: MoveOperationPayload;
  nodeMoveResult: NodeMoveResult;
  nodeVisibility: NodeVisibility;
  opaqueId: OpaqueId;
  operation: Operation;
  operationResult: OperationResult;
  operationSource: OperationSource;
  orderKey: OrderKey;
  pollHint: PollHint;
  principalId: PrincipalId;
  principalRef: PrincipalRef;
  problem: Problem;
  problemFieldError: ProblemFieldError;
  profileName: ProfileName;
  provenance: Provenance;
  publication: Publication;
  publishReleasePlanOperation: PublishReleasePlanOperation;
  rateLimitDirectory: RateLimitDirectory;
  rateLimitPolicy: RateLimitPolicy;
  rateLimitPolicyPatch: RateLimitPolicyPatch;
  rateLimitPolicyUpdateRequest: RateLimitPolicyUpdateRequest;
  rateLimitScope: RateLimitScope;
  readingStateValue: ReadingStateValue;
  relation: Relation;
  relationCreate: RelationCreate;
  relationMergePatch: RelationMergePatch;
  relationUpdateOperationPayload: RelationUpdateOperationPayload;
  release: Release;
  releaseCreate: ReleaseCreate;
  releaseDirectory: ReleaseDirectory;
  releaseLinks: ReleaseLinks;
  releasePublishedFeedEventData: ReleasePublishedFeedEventData;
  releaseResult: ReleaseResult;
  reorderOperationPayload: ReorderOperationPayload;
  replica: Replica;
  replicaAdapter: ReplicaAdapter;
  replicaBinding: ReplicaBinding;
  replicaCapabilities: ReplicaCapabilities;
  replicaLease: ReplicaLease;
  restoreOperationPayload: RestoreOperationPayload;
  revokeKeyPlanOperation: RevokeKeyPlanOperation;
  rootCreate: RootCreate;
  rotateKeyPlanOperation: RotateKeyPlanOperation;
  scopeName: ScopeName;
  serviceUrl: ServiceUrl;
  setAccessPolicyPlanOperation: SetAccessPolicyPlanOperation;
  setRateLimitPlanOperation: SetRateLimitPlanOperation;
  setVisibilityPlanOperation: SetVisibilityPlanOperation;
  snapshot: Snapshot;
  snapshotPage: SnapshotPage;
  snapshotQuery: SnapshotQuery;
  sourceRef: SourceRef;
  subject: Subject;
  syncAckRequest: SyncAckRequest;
  syncAckResult: SyncAckResult;
  syncCollectionPush: SyncCollectionPush;
  syncCollectionSessionRequest: SyncCollectionSessionRequest;
  syncCollectionSessionResult: SyncCollectionSessionResult;
  syncInstanceCreatePush: SyncInstanceCreatePush;
  syncInstanceSessionRequest: SyncInstanceSessionRequest;
  syncInstanceSessionResult: SyncInstanceSessionResult;
  syncMirrorPlanInput: SyncMirrorPlanInput;
  syncMirrorPlanOperation: SyncMirrorPlanOperation;
  syncPull: SyncPull;
  manifestV02: ManifestV02;
  syncPullV02: SyncPullV02;
  syncPullEventV02: SyncPullEventV02;
  syncSnapshotV02: SyncSnapshotV02;
  authoritativeEffectPage: AuthoritativeEffectPage;
  authoritativePullEffect: AuthoritativePullEffect;
  syncPullEvent: SyncPullEvent;
  syncPullQuery: SyncPullQuery;
  syncPush: SyncPush;
  syncPushResult: SyncPushResult;
  syncSessionCollectionRequest: SyncSessionCollectionRequest;
  syncSessionCollectionResult: SyncSessionCollectionResult;
  syncSessionRequest: SyncSessionRequest;
  syncSessionRequestV02: SyncSessionRequestV02;
  syncSessionResult: SyncSessionResult;
  syncSessionResultV02: SyncSessionResultV02;
  syncSnapshotQuery: SyncSnapshotQuery;
  syncTombstone: SyncTombstone;
  urlHash: UrlHash;
  visibility: Visibility;
  visibilityPlanInput: VisibilityPlanInput;
  warning: Warning;
  webSubHub: WebSubHub;
}
export interface AccessEntry {
  principal: PrincipalRef;
  effect: 'allow' | 'deny';
  /**
   * @minItems 1
   */
  scopes: [ScopeName, ...ScopeName[]];
}
export interface PrincipalRef {
  type: 'user' | 'group' | 'oauth_client' | 'api_key' | 'service' | 'ai_agent' | 'public';
  id: PrincipalId;
}
export interface AccessPolicy {
  visibility: Visibility;
  entries: AccessEntry[];
  publication: AccessPublicationPolicy;
  revision: OpaqueId;
}
export interface AccessPublicationPolicy {
  listInDirectory: boolean;
  allowSearchIndexing: boolean;
  allowEmbedding: boolean;
}
export interface AccessPolicyPatch {
  visibility?: Visibility;
  entries?: AccessEntry[];
  publication?: AccessPublicationPolicy;
}
export interface AccessPublicationChangedFeedEventData {
  collectionId: OpaqueId;
  revision: OpaqueId;
  visibility: Visibility;
}
export interface ReplicaLease {
  leaseId: OpaqueId;
  generation: OpaqueId;
  state: 'active' | 'expired' | 'recovery_required' | 'retired';
  lastSeenAt: DateTime;
  expiresAt: DateTime;
  acknowledgedCursor: null | OpaqueId;
}
export interface Actor {
  id: AbsoluteUri;
  name: string;
  url?: HttpUrl;
  avatar?: HttpUrl;
}
export interface Subject {
  type: 'collection' | 'node';
  id: OpaqueId;
}
export interface Extensions {
  [k: string]: unknown;
}
export interface AnnotationMergePatch {
  format?: string | null;
  value?: unknown;
  visibility?: Visibility;
  provenance?: null | Provenance;
  extensions?: null | Extensions;
}
export interface AnnotationUpdateOperationPayload {
  base: AnnotationMergePatch;
  value: AnnotationMergePatch;
}
export interface ApiKeyCreateRequest {
  name: string;
  type: 'read_key' | 'sync_key' | 'publisher_key' | 'admin_key' | 'one_time_key';
  /**
   * @minItems 1
   */
  scopes: [ScopeName, ...ScopeName[]];
  collections: OpaqueId[];
  expiresAt: null | DateTime;
}
export interface ApiKeyCreateResult {
  key: ApiKeyMetadata;
  secret: string;
}
export interface ApiKeyMetadata {
  id: OpaqueId;
  name: string;
  type: 'read_key' | 'sync_key' | 'publisher_key' | 'admin_key' | 'one_time_key';
  /**
   * @minItems 1
   */
  scopes: [ScopeName, ...ScopeName[]];
  collections: OpaqueId[];
  createdAt: DateTime;
  expiresAt: null | DateTime;
  lastUsedAt: null | DateTime;
  lastUsedIp: string | null;
  status: 'active' | 'rotating' | 'revoked' | 'expired';
}
export interface ApiKeyDirectory {
  keys: ApiKeyMetadata[];
  nextCursor: null | OpaqueId;
}
export interface ApiKeyRevokeResult {
  key: ApiKeyMetadata;
  revokedAt: DateTime;
}
export interface ApiKeyRotateRequest {
  overlapSeconds: number;
}
export interface Attachment {
  id: OpaqueId;
  collectionId: OpaqueId;
  subject: Subject;
  rel: string;
  url: HttpUrl;
  mimeType?: string;
  title?: string;
  size?: number;
  digest?: string;
  visibility: Visibility;
  createdAt: DateTime;
  updatedAt: DateTime;
  revision: OpaqueId;
  extensions?: Extensions;
}
export interface AttachmentCreate {
  subject: Subject;
  rel: string;
  url: HttpUrl;
  mimeType?: string;
  title?: string;
  size?: number;
  digest?: string;
  visibility: Visibility;
  extensions?: Extensions;
}
export interface AttachmentMergePatch {
  rel?: string;
  url?: null | HttpUrl;
  mimeType?: string | null;
  title?: string | null;
  size?: number | null;
  digest?: string | null;
  visibility?: Visibility;
  extensions?: null | Extensions;
}
export interface AttachmentUpdateOperationPayload {
  base: AttachmentMergePatch;
  value: AttachmentMergePatch;
}
export interface AuditActor {
  principalId: PrincipalId;
  clientId?: AbsoluteUri;
  agent?: string;
}
export interface AuditConfirmation {
  required: boolean;
  method: string;
  confirmedAt: null | DateTime;
}
export interface AuditDirectory {
  events: AuditEvent[];
  nextCursor: null | OpaqueId;
}
export interface AuditEvent {
  id: OpaqueId;
  time: DateTime;
  actor: AuditActor;
  action: string;
  target: string;
  result: 'success' | 'failure' | 'denied';
  risk: 'low' | 'medium' | 'high';
  confirmation?: AuditConfirmation;
  metadata?: {
    [k: string]: unknown;
  };
}
export interface AuditQuery {
  cursor?: OpaqueId;
  limit?: number;
  action?: string;
  result?: 'success' | 'failure' | 'denied';
  from?: DateTime;
  to?: DateTime;
}
export interface ChangeCommitRequest {
  planId: OpaqueId;
}
export interface ChangeCommitResult {
  planId: OpaqueId;
  committedAt: DateTime;
  operations: OperationResult[];
}
export interface SyncSessionCollectionResult {
  collectionId: OpaqueId;
  snapshotRequired: boolean;
  serverCursor: OpaqueId;
  serverRevision: OpaqueId;
}
export interface Warning {
  code: string;
  message: string;
  nodeId?: OpaqueId;
  path?: string;
  lossy?: boolean;
}
export interface ChangeCounts {
  created: number;
  updated: number;
  moved: number;
  deleted: number;
}
export interface ChangePlanImpact {
  collections: number;
  nodes: number;
  annotations: number;
  attachments: number;
  relations: number;
  privateFieldsExcluded: string[];
}
export interface DeleteCollectionPlanOperation {
  type: 'delete_collection';
  collectionId: OpaqueId;
  baseRevision: OpaqueId;
}
export interface DeleteSubtreePlanOperation {
  type: 'delete_subtree';
  collectionId: OpaqueId;
  targetId: OpaqueId;
  baseRevision: OpaqueId;
}
export interface SetVisibilityPlanOperation {
  type: 'set_visibility';
  collectionId: OpaqueId;
  baseRevision: OpaqueId;
  input: VisibilityPlanInput;
}
export interface VisibilityPlanInput {
  visibility: Visibility;
}
export interface SetAccessPolicyPlanOperation {
  type: 'set_access_policy';
  collectionId: OpaqueId;
  baseRevision: OpaqueId;
  input: AccessPolicyPatch;
}
export interface CreateKeyPlanOperation {
  type: 'create_key';
  input: ApiKeyCreateRequest;
}
export interface RotateKeyPlanOperation {
  type: 'rotate_key';
  targetId: OpaqueId;
  input: ApiKeyRotateRequest;
}
export interface RevokeKeyPlanOperation {
  type: 'revoke_key';
  targetId: OpaqueId;
}
export interface SetRateLimitPlanOperation {
  type: 'set_rate_limit';
  targetId: PrincipalId;
  baseRevision: OpaqueId;
  input: RateLimitPolicyPatch;
}
export interface RateLimitPolicyPatch {
  scope?: RateLimitScope;
  limit?: number;
  windowSeconds?: number;
  burst?: number;
  concurrency?: number;
  minIntervalMilliseconds?: number;
  action?: 'reject' | 'delay';
}
export interface RateLimitScope {
  endpointClass?: string;
  principalType?: string;
  collectionId?: OpaqueId;
}
export interface PublishReleasePlanOperation {
  type: 'publish_release';
  collectionId: OpaqueId;
  baseRevision: OpaqueId;
  input: ReleaseCreate;
}
export interface ReleaseCreate {
  title?: string;
  summary?: string;
  note?: string;
  extensions?: Extensions;
}
export interface SyncMirrorPlanOperation {
  type: 'sync_mirror';
  collectionId: OpaqueId;
  baseRevision: OpaqueId;
  input: SyncMirrorPlanInput;
}
export interface SyncMirrorPlanInput {
  replicaId: OpaqueId;
}
export interface ChangePlanRequest {
  /**
   * @minItems 1
   */
  operations: [ChangePlanOperation, ...ChangePlanOperation[]];
  reason: string;
  dryRun: true;
}
export interface Collection {
  schemaVersion: '0.1';
  id: OpaqueId;
  canonicalUrl?: HttpUrl;
  slug?: string;
  kind: 'bookmarks' | 'reading_path' | 'knowledge_collection' | 'mixed';
  title: string;
  summary?: string;
  description?: FormattedText;
  language?: string;
  tags?: string[];
  icon?: Media;
  cover?: Media;
  /**
   * @maxItems 512
   */
  creators?: Actor[];
  rootNodeId: OpaqueId;
  visibility: Visibility;
  publication?: Publication;
  createdAt: DateTime;
  updatedAt: DateTime;
  revision: OpaqueId;
  eventCursor?: OpaqueId;
  extensions?: Extensions;
}
export interface FormattedText {
  format: 'plain' | 'markdown' | 'html';
  value: string;
}
export interface Media {
  url: HttpUrl;
  mimeType?: string;
  width?: number;
  height?: number;
}
export interface Publication {
  feedMode: 'live' | 'release' | 'disabled';
  includeNodeContent?: 'metadata' | 'summary' | 'full';
  includeRelations?: boolean;
}
export interface CollectionCreate {
  canonicalUrl?: HttpUrl;
  slug?: string;
  kind: 'bookmarks' | 'reading_path' | 'knowledge_collection' | 'mixed';
  title: string;
  summary?: string;
  description?: FormattedText;
  language?: string;
  tags?: string[];
  icon?: Media;
  cover?: Media;
  /**
   * @maxItems 512
   */
  creators?: Actor[];
  visibility: Visibility;
  publication?: Publication;
  extensions?: Extensions;
}
export interface CreateCollectionOperationPayload {
  collection: CollectionCreate;
  root: RootCreate;
}
export interface RootCreate {
  title: string;
  folderRole: 'root';
  extensions?: Extensions;
}
export interface CollectionCreateResult {
  collection: Collection;
  root: Node;
  links: CollectionLinks;
}
export interface NodeConstraints {
  readOnly: boolean;
  reason?: string | null;
}
export interface SourceRef {
  system: string;
  adapterVersion?: string;
  replicaId: OpaqueId;
  profileId?: OpaqueId;
  nativeId: string;
  nativeParentId?: null | string;
  nativeIndex?: number | null;
  nativeCreatedAt?: number | null;
  nativeModifiedAt?: number | null;
  nativeType?: string | null;
  rootRole?: string | null;
  syncing?: boolean | null;
  capturedAt: DateTime;
}
export interface CollectionLinks {
  self: HttpUrl;
  canonical: HttpUrl;
  snapshot: HttpUrl;
  node?: HttpUrl;
  nodes?: HttpUrl;
  annotations?: HttpUrl;
  attachments?: HttpUrl;
  relations?: HttpUrl;
  feed?: HttpUrl;
  releases?: HttpUrl;
  release?: HttpUrl;
  access?: HttpUrl;
  alternateJsonFeed?: HttpUrl;
  alternateAtom?: HttpUrl;
}
export interface CollectionDirectory {
  protocolVersion: '0.1';
  collections: DirectoryCollection[];
  nextCursor: null | OpaqueId;
}
export interface DirectoryCollection {
  id: OpaqueId;
  canonicalUrl: HttpUrl;
  title: string;
  summary?: string;
  kind: 'bookmarks' | 'reading_path' | 'knowledge_collection' | 'mixed';
  tags?: string[];
  language?: string;
  /**
   * @maxItems 512
   */
  creators?: Actor[];
  nodeCount: number;
  updatedAt: DateTime;
  visibility: Visibility;
  links: CollectionLinks;
  extensions?: Extensions;
}
export interface CollectionFeedEventData {
  collectionId: OpaqueId;
  revision: OpaqueId;
  summary?: string;
}
export interface CollectionMergePatch {
  canonicalUrl?: null | HttpUrl;
  slug?: string | null;
  title?: string;
  summary?: string | null;
  description?: null | FormattedText;
  language?: string | null;
  tags?: null | string[];
  icon?: null | Media;
  cover?: null | Media;
  creators?: null | Actor[];
  visibility?: Visibility;
  publication?: null | Publication;
  extensions?: null | Extensions;
}
export interface CollectionMetadata {
  collection: Collection;
  links: CollectionLinks;
}
export interface CollectionMetadataUpdateOperationPayload {
  base: CollectionMergePatch;
  value: CollectionMergePatch;
}
export interface Conflict {
  id: OpaqueId;
  collectionId: OpaqueId;
  targetId: OpaqueId;
  type: string;
  field?: string;
  base?: unknown;
  server?: unknown;
  incoming?: unknown;
  incomingOpId?: OpaqueId;
  createdAt: DateTime;
  status: 'open' | 'resolved';
  /**
   * @minItems 1
   */
  allowedResolutions: [
    'server' | 'incoming' | 'custom' | 'both',
    ...('server' | 'incoming' | 'custom' | 'both')[],
  ];
  revision: OpaqueId;
}
export interface ConflictResolutionResult {
  conflict: Conflict;
  operation: Operation;
  cursor: OpaqueId;
}
export interface OperationSource {
  adapterProfile?: string;
  nativeEvent?: string;
  extensions?: Extensions;
}
export interface ConversionPolicy {
  alias: 'duplicate' | 'skip' | 'reject';
  separator: 'native' | 'omit' | 'preserve_remote' | 'reject';
  unknownExtensions: 'preserve_remote' | 'sidecar' | 'reject';
}
export interface ConversionPreview {
  creates: number;
  updates: number;
  moves: number;
  deletes: number;
  sidecarOnly: number;
  lossy: number;
  warnings: Warning[];
}
export interface CreateAnnotationOperationPayload {
  annotation: AnnotationCreate;
}
export interface CreateAttachmentOperationPayload {
  attachment: AttachmentCreate;
}
export interface CreateNodeOperationPayload {
  parentId: OpaqueId;
  afterId?: null | OpaqueId;
  beforeId?: null | OpaqueId;
  node: NodeCreate;
}
export interface CreateRelationOperationPayload {
  relation: RelationCreate;
}
export interface RelationCreate {
  type:
    | 'related'
    | 'precedes'
    | 'follows'
    | 'supports'
    | 'contradicts'
    | 'duplicate_of'
    | 'derived_from'
    | 'mentions'
    | 'custom';
  fromNodeId: OpaqueId;
  toNodeId: OpaqueId;
  label?: string;
  visibility: Visibility;
  extensions?: Extensions;
}
export interface CursorPageQuery {
  cursor?: OpaqueId;
  limit?: number;
}
export interface DeleteOperationPayload {
  reason?: string;
}
export interface DeleteResult {
  receipt: DeletionReceipt;
}
export interface DeletionReceipt {
  resourceType: 'collection' | 'node' | 'annotation' | 'attachment' | 'relation';
  targetId: OpaqueId;
  collectionId: OpaqueId;
  scope: 'single' | 'subtree';
  deletedAt: DateTime;
  deletedBy?: PrincipalId;
  deleteRevision: OpaqueId;
  operationId: OpaqueId;
  affectedCount: number;
  purgeAfter: DateTime;
}
export interface DirectoryQuery {
  cursor?: OpaqueId;
  limit?: number;
  tag?: string;
  creator?: string;
  kind?: 'bookmarks' | 'reading_path' | 'knowledge_collection' | 'mixed';
  updatedSince?: DateTime;
  q?: string;
}
export interface ExtensionFeedEventData {
  collectionId: OpaqueId;
  extensions: Extensions;
}
export interface Feed {
  protocolVersion: '0.1';
  feedUrl: HttpUrl;
  collectionUrl: HttpUrl;
  title: string;
  events: FeedEvent[];
  nextCursor: OpaqueId;
  hasMore: boolean;
  poll: PollHint;
  /**
   * @maxItems 512
   */
  hubs: WebSubHub[];
}
export interface PollHint {
  notBefore: DateTime;
  recommendedAfterSeconds: number;
}
export interface WebSubHub {
  type: 'WebSub';
  url: HttpsUrl;
}
export interface ReleasePublishedFeedEventData {
  collectionId: OpaqueId;
  revision: OpaqueId;
  summary?: string;
  changes: ChangeCounts;
  releaseId: OpaqueId;
  snapshotUrl: HttpUrl;
  snapshotDigest: string;
}
export interface NodeChangedFeedEventData {
  collectionId: OpaqueId;
  revision: OpaqueId;
  node: FeedNode;
}
export interface NodeDeletedFeedEventData {
  collectionId: OpaqueId;
  revision: OpaqueId;
  nodeId: OpaqueId;
  summary?: string;
}
export interface FeedQuery {
  cursor?: OpaqueId;
  from?: 'now' | 'beginning';
  limit?: number;
}
export interface GlobalResourceIdentity {
  serverUuid: OpaqueId;
  resourceType: GlobalResourceType;
  id: OpaqueId;
}
export interface HighlightValue {
  quote: string;
  sourceUrl?: HttpUrl;
  selector?: {
    type: 'TextQuoteSelector';
    exact: string;
    prefix?: string;
    suffix?: string;
  };
  comment?: string;
}
export interface Manifest {
  protocol: 'https://collectionprotocol.org/spec/0.1';
  /**
   * @minItems 1
   */
  protocolVersions: [string, ...string[]];
  serverId: ServiceUrl;
  serverUuid: OpaqueId;
  title: string;
  /**
   * @minItems 1
   */
  mounts: [ManifestMount, ...ManifestMount[]];
  signing?: ManifestSigning;
}
export interface ManifestEndpoints {
  directory?: HttpsUriTemplate & HttpsUriTemplate1;
  collection?: HttpsUriTemplate & HttpsUriTemplate1;
  snapshot?: HttpsUriTemplate & HttpsUriTemplate1;
  node?: HttpsUriTemplate & HttpsUriTemplate1;
  nodes?: HttpsUriTemplate & HttpsUriTemplate1;
  nodeMove?: HttpsUriTemplate & HttpsUriTemplate1;
  annotations?: HttpsUriTemplate & HttpsUriTemplate1;
  annotation?: HttpsUriTemplate & HttpsUriTemplate1;
  attachments?: HttpsUriTemplate & HttpsUriTemplate1;
  attachment?: HttpsUriTemplate & HttpsUriTemplate1;
  relations?: HttpsUriTemplate & HttpsUriTemplate1;
  relation?: HttpsUriTemplate & HttpsUriTemplate1;
  release?: HttpsUriTemplate & HttpsUriTemplate1;
  releases?: HttpsUriTemplate & HttpsUriTemplate1;
  releaseItem?: HttpsUriTemplate & HttpsUriTemplate1;
  releaseSnapshot?: HttpsUriTemplate & HttpsUriTemplate1;
  collectionAccess?: HttpsUriTemplate & HttpsUriTemplate1;
  instanceFeed?: HttpsUriTemplate & HttpsUriTemplate1;
  collectionFeed?: HttpsUriTemplate & HttpsUriTemplate1;
  syncSessions?: HttpsUriTemplate & HttpsUriTemplate1;
  syncSnapshot?: HttpsUriTemplate & HttpsUriTemplate1;
  syncPush?: HttpsUriTemplate & HttpsUriTemplate1;
  syncPull?: HttpsUriTemplate & HttpsUriTemplate1;
  syncAck?: HttpsUriTemplate & HttpsUriTemplate1;
  syncConflict?: HttpsUriTemplate & HttpsUriTemplate1;
  mcp?: HttpsUriTemplate & HttpsUriTemplate1;
  adminAccess?: HttpsUriTemplate & HttpsUriTemplate1;
  adminKeys?: HttpsUriTemplate & HttpsUriTemplate1;
  adminKey?: HttpsUriTemplate & HttpsUriTemplate1;
  adminKeyRotate?: HttpsUriTemplate & HttpsUriTemplate1;
  adminRateLimits?: HttpsUriTemplate & HttpsUriTemplate1;
  adminAudit?: HttpsUriTemplate & HttpsUriTemplate1;
}
export interface ManifestFeatures {
  feed?: {
    /**
     * @minItems 1
     */
    modes: ['live' | 'release', ...('live' | 'release')[]];
  };
  patch?: {
    /**
     * @minItems 1
     */
    mediaTypes: [
      'application/merge-patch+json' | 'application/json-patch+json',
      ...('application/merge-patch+json' | 'application/json-patch+json')[],
    ];
  };
  bookmarkUrls?: {
    /**
     * @minItems 2
     */
    acceptedSchemes: {
      [k: string]: unknown;
    } & [string, string, ...string[]];
  };
  sync?: {
    multiCollectionSessions: boolean;
  };
  mcp?: {
    protocolVersion: '2026-07-28';
    resources: boolean;
    tools: boolean;
  };
  admin?: {
    access: boolean;
    keys: boolean;
    rateLimits: boolean;
    audit: boolean;
  };
}
export interface ManifestLimits {
  maxPageSize: number;
  maxSnapshotNodes: number;
  minPollIntervalSeconds: number;
  recommendedPollIntervalSeconds: number;
  maxSyncBatchOperations?: number;
  idempotencyRetentionSeconds?: number;
  syncCursorRetentionSeconds?: number;
}
export interface McpTool {
  name: string;
  title?: string;
  description?: string;
  inputSchema: {
    [k: string]: unknown;
  };
  outputSchema?: {
    [k: string]: unknown;
  };
  _meta?: {
    [k: string]: unknown;
  };
}
export interface McpToolsList {
  jsonrpc: '2.0';
  id: string | number;
  result: {
    resultType?: 'complete';
    ttlMs?: number;
    cacheScope?: 'public' | 'private';
    tools: McpTool[];
    nextCursor?: OpaqueId;
  };
}
export interface MoveOperationPayload {
  newParentId: OpaqueId;
  afterId?: null | OpaqueId;
  beforeId?: null | OpaqueId;
  baseSourceParentRevision: OpaqueId;
  baseTargetParentRevision: OpaqueId;
}
export interface NodeContentUpdateOperationPayload {
  base: NodeMergePatch;
  value: NodeMergePatch;
}
export interface NodeMergePatch {
  title?: string | null;
  url?: null | BookmarkUrl;
  canonicalUrl?: null | HttpUrl;
  urlHash?: null | UrlHash;
  targetNodeId?: null | OpaqueId;
  folderRole?: null | FolderRole;
  description?: string | null;
  tags?: null | string[];
  visibility?: null | NodeVisibility;
  constraints?: null | NodeConstraints;
  extensions?: null | Extensions;
}
export interface NodeDeleteQuery {
  recursive?: boolean;
}
export interface NodeDetail {
  node: Node;
  included: NodeIncluded;
  links?: CollectionLinks;
}
export interface NodeIncluded {
  annotations?: Annotation[];
  attachments?: Attachment[];
  relations?: Relation[];
}
export interface Relation {
  id: OpaqueId;
  collectionId: OpaqueId;
  type:
    | 'related'
    | 'precedes'
    | 'follows'
    | 'supports'
    | 'contradicts'
    | 'duplicate_of'
    | 'derived_from'
    | 'mentions'
    | 'custom';
  fromNodeId: OpaqueId;
  toNodeId: OpaqueId;
  label?: string;
  visibility: Visibility;
  createdAt: DateTime;
  updatedAt: DateTime;
  revision: OpaqueId;
  extensions?: Extensions;
}
export interface NodeDetailQuery {
  include?: ('annotations' | 'attachments' | 'relations')[];
}
export interface NodeMoveResult {
  node: Node;
  sourceParentRevision: OpaqueId;
  targetParentRevision: OpaqueId;
  position: OrderKey;
  warnings: Warning[];
}
export interface Problem {
  type: AbsoluteUri;
  title: string;
  status: number;
  code: (
    | (
        | 'invalid_json'
        | 'invalid_query'
        | 'invalid_cursor_scope'
        | 'authentication_required'
        | 'insufficient_scope'
        | 'node_read_only'
        | 'origin_not_allowed'
        | 'csrf_failed'
        | 'resource_not_found'
        | 'method_not_allowed'
        | 'unsupported_version'
        | 'revision_conflict'
        | 'position_context_stale'
        | 'snapshot_expired'
        | 'idempotency_key_reused'
        | 'idempotency_in_progress'
        | 'sequence_gap'
        | 'sequence_blocked'
        | 'sequence_reuse'
        | 'op_id_reused'
        | 'dependency_failed'
        | 'folder_not_empty'
        | 'feed_cursor_expired'
        | 'sync_cursor_expired'
        | 'stale_replica'
        | 'replica_retired'
        | 'resource_purged'
        | 'precondition_failed'
        | 'payload_too_large'
        | 'unsupported_media_type'
        | 'unsupported_operation'
        | 'invalid_document'
        | 'precondition_required'
        | 'rate_limited'
        | 'internal_error'
        | 'service_unavailable'
      )
    | {
        [k: string]: unknown;
      }
  ) &
    string;
  detail?: string;
  instance?: string;
  currentRevision?: OpaqueId;
  currentEtag?: string;
  expectedSequence?: number;
  supportedVersions?: string[];
  retryAfterSeconds?: number;
  snapshotUrl?: HttpUrl;
  conflictId?: OpaqueId;
  retryable?: boolean;
  errors?: ProblemFieldError[];
  links?: {
    [k: string]: HttpUrl;
  };
}
export interface ProblemFieldError {
  path: string;
  keyword: string;
  message: string;
}
export interface RateLimitDirectory {
  policies: RateLimitPolicy[];
}
export interface RateLimitPolicy {
  id: PrincipalId;
  scope: RateLimitScope;
  limit: number;
  windowSeconds: number;
  burst: number;
  concurrency: number;
  minIntervalMilliseconds: number;
  action: 'reject' | 'delay';
  revision: OpaqueId;
}
export interface RateLimitPolicyUpdateRequest {
  id: PrincipalId;
  patch: RateLimitPolicyPatch;
}
export interface ReadingStateValue {
  status: 'unread' | 'in_progress' | 'completed' | 'archived';
  progress: number;
  completedAt: null | DateTime;
}
export interface RelationMergePatch {
  type?:
    | 'related'
    | 'precedes'
    | 'follows'
    | 'supports'
    | 'contradicts'
    | 'duplicate_of'
    | 'derived_from'
    | 'mentions'
    | 'custom';
  label?: string | null;
  visibility?: Visibility;
  extensions?: null | Extensions;
}
export interface RelationUpdateOperationPayload {
  base: RelationMergePatch;
  value: RelationMergePatch;
}
export interface Release {
  id: OpaqueId;
  collectionId: OpaqueId;
  revision: OpaqueId;
  title?: string;
  summary?: string;
  note?: string;
  publishedAt: DateTime;
  publishedBy?: Actor;
  snapshotUrl: HttpUrl;
  contentDigest: string;
  changes: ChangeCounts;
  extensions?: Extensions;
}
export interface ReleaseDirectory {
  protocolVersion: '0.1';
  releases: Release[];
  nextCursor: null | OpaqueId;
}
export interface ReleaseLinks {
  self: HttpUrl;
  snapshot: HttpUrl;
  collection: HttpUrl;
}
export interface ReleaseResult {
  release: Release;
  links: ReleaseLinks;
}
export interface ReorderOperationPayload {
  parentId: OpaqueId;
  /**
   * @minItems 1
   */
  childIds: [OpaqueId, ...OpaqueId[]];
  baseChildrenRevision: OpaqueId;
}
export interface ReplicaAdapter {
  profile: string;
  version: string;
}
export interface ReplicaCapabilities {
  read: boolean;
  write: boolean;
  events: boolean;
  separator: boolean;
  alias: boolean;
  annotations: 'native' | 'sidecar' | 'none';
  maxBatchOperations: number;
}
export interface RestoreOperationPayload {
  newParentId?: OpaqueId;
  afterId?: null | OpaqueId;
  beforeId?: null | OpaqueId;
  reason?: string;
}
export interface SyncTombstone {
  resourceType: 'collection' | 'node' | 'annotation' | 'attachment' | 'relation';
  targetId: OpaqueId;
  collectionId: OpaqueId;
  scope: 'single' | 'subtree';
  deletedAt: DateTime;
  deletedBy?: PrincipalId;
  deleteRevision: OpaqueId;
  operationId: OpaqueId;
  deleteCursor: OpaqueId;
  affectedCount: number;
  purgeAfter: DateTime;
}
export interface SnapshotQuery {
  pageCursor?: OpaqueId;
  limit?: number;
  include?: ('annotations' | 'attachments' | 'relations')[];
  depth?: number;
  root?: OpaqueId;
}
export interface SyncAckRequest {
  sessionId: OpaqueId;
  cursor: OpaqueId;
  recoveryCapability?: OpaqueId;
  warnings: Warning[];
}
export interface SyncAckResult {
  replicaId: OpaqueId;
  ackedCursor: OpaqueId;
  ackedAt: DateTime;
}
export interface SyncCollectionPush {
  sessionId: OpaqueId;
  batchId: OpaqueId;
  atomic: boolean;
  /**
   * @minItems 1
   */
  operations: [Operation, ...Operation[]];
}
export interface SyncCollectionSessionRequest {
  protocolVersion: '0.1';
  replica: Replica;
  scope: 'collection';
  collection: SyncSessionCollectionRequest;
  clientTime: DateTime;
}
export interface SyncSessionCollectionRequest {
  collectionId: OpaqueId;
  lastCursor: null | OpaqueId;
  lastRevision: null | OpaqueId;
  bootstrapMode: 'download' | 'upload' | 'merge' | 'mirror';
}
export interface SyncCollectionSessionResult {
  sessionId: OpaqueId;
  expiresAt: DateTime;
  serverTime: DateTime;
  clockSkewMilliseconds: number;
  acceptedProtocolVersion: '0.1';
  scope: 'collection';
  maxBatchOperations: number;
  tombstoneRetentionSeconds: number;
  replicaLease: ActiveReplicaLease;
  collection: SyncSessionCollectionResult;
  conversionPolicy: ConversionPolicy;
}
export interface SyncInstanceCreatePush {
  sessionId: OpaqueId;
  batchId: OpaqueId;
  atomic: true;
  /**
   * @minItems 1
   * @maxItems 1
   */
  operations: [
    Operation & {
      type: 'create_collection';
      [k: string]: unknown;
    },
  ];
}
export interface SyncInstanceSessionRequest {
  protocolVersion: '0.1';
  replica: Replica;
  scope: 'instance';
  purpose: 'create_collection';
  clientTime: DateTime;
}
export interface SyncInstanceSessionResult {
  sessionId: OpaqueId;
  expiresAt: DateTime;
  serverTime: DateTime;
  clockSkewMilliseconds: number;
  acceptedProtocolVersion: '0.1';
  scope: 'instance';
  purpose: 'create_collection';
  maxBatchOperations: 1;
  tombstoneRetentionSeconds: number;
  replicaLease: ActiveReplicaLease;
  conversionPolicy: ConversionPolicy;
}
export interface SyncPull {
  events: SyncPullEvent[];
  nextCursor: OpaqueId;
  hasMore: boolean;
  collectionRevision: OpaqueId;
  recommendedPullAfterSeconds: number;
}
export interface SyncPullQuery {
  sessionId: OpaqueId;
  cursor?: OpaqueId;
  limit?: number;
}
/** COLP 0.2 RFC 9530 SHA-256 Content-Digest field value. */
export type AuthoritativeDigest = string;
export type ManifestV02 = Omit<Manifest, 'protocol'> & {
  protocol: 'https://collectionprotocol.org/spec/0.2';
  protocolVersions: [string, string, ...string[]];
  syncEffectPages: HttpsUriTemplate;
};
export interface AuthoritativeEffectBinding {
  effectId: OpaqueId;
  status: 'applied' | 'rebased';
  opId: OpaqueId;
  replicaId: OpaqueId;
  sequence: number;
  collectionId: OpaqueId;
  operationDigest: AuthoritativeDigest;
  effectDigest: AuthoritativeDigest;
}
export interface AuthoritativePlacement {
  parentId: OpaqueId;
  afterId: OpaqueId | null;
  beforeId: OpaqueId | null;
  position: OrderKey;
}
export interface AuthoritativeParentRevision {
  parentId: OpaqueId;
  childrenRevision: OpaqueId;
}
export interface AuthoritativeEffectPageRef {
  pageCount: number;
  memberCount: number;
  memberDigest: AuthoritativeDigest;
  firstPageDigest: AuthoritativeDigest;
}
export interface AuthoritativeEffectPage {
  effectId: OpaqueId;
  pageNumber: number;
  pageCount: number;
  members: OpaqueId[];
  memberCount: number;
  pageDigest: AuthoritativeDigest;
  previousPageDigest: AuthoritativeDigest | null;
}
export type NodeCreatedEffect = AuthoritativeEffectBinding & {
  kind: 'node_created'; node: Node; placement: AuthoritativePlacement;
  parentRevision: AuthoritativeParentRevision;
  nodeChildrenRevision: OpaqueId | null;
};
export type NodeContentUpdatedEffect = AuthoritativeEffectBinding & {
  kind: 'node_content_updated'; node: Node;
};
export type NodeMovedEffect = AuthoritativeEffectBinding & {
  kind: 'node_moved'; node: Node; placement: AuthoritativePlacement;
  parentRevisions: AuthoritativeParentRevision[];
};
export type NodeDeletedEffect = AuthoritativeEffectBinding & {
  kind: 'node_deleted'; deletion: SyncTombstone; tombstone: SyncTombstone;
  parentRevision: AuthoritativeParentRevision;
};
export type SubtreeDeletedEffect = AuthoritativeEffectBinding & {
  kind: 'subtree_deleted'; rootTombstone: SyncTombstone; memberCount: number;
  memberDigest: AuthoritativeDigest; parentRevision: AuthoritativeParentRevision;
} & ({ members: OpaqueId[]; effectRef?: never } | { members?: never; effectRef: AuthoritativeEffectPageRef });
export type NodeRestoredEffect = AuthoritativeEffectBinding & {
  kind: 'node_restored'; node: Node; placement: AuthoritativePlacement;
  parentRevision: AuthoritativeParentRevision; consumedTombstone: SyncTombstone;
};
export type AuthoritativePullEffect =
  | NodeCreatedEffect | NodeContentUpdatedEffect | NodeMovedEffect | NodeDeletedEffect
  | SubtreeDeletedEffect | NodeRestoredEffect;
export type SyncPullEventV02 =
  | { cursor: OpaqueId; kind: 'operation'; operation: Extract<Operation, { type: 'create_node' }>; effect: NodeCreatedEffect; conflict?: never }
  | { cursor: OpaqueId; kind: 'operation'; operation: Extract<Operation, { type: 'update_node_content' }>; effect: NodeContentUpdatedEffect; conflict?: never }
  | { cursor: OpaqueId; kind: 'operation'; operation: Extract<Operation, { type: 'move_node' }>; effect: NodeMovedEffect; conflict?: never }
  | { cursor: OpaqueId; kind: 'operation'; operation: Extract<Operation, { type: 'delete_node' }>; effect: NodeDeletedEffect; conflict?: never }
  | { cursor: OpaqueId; kind: 'operation'; operation: Extract<Operation, { type: 'delete_subtree' }>; effect: SubtreeDeletedEffect; conflict?: never }
  | { cursor: OpaqueId; kind: 'operation'; operation: Extract<Operation, { type: 'restore_node' }>; effect: NodeRestoredEffect; conflict?: never }
  | { cursor: OpaqueId; kind: 'conflict'; conflict: Conflict; operation?: never; effect?: never };
export interface SyncPullV02 {
  events: SyncPullEventV02[];
  nextCursor: OpaqueId;
  hasMore: boolean;
  collectionRevision: OpaqueId;
  recommendedPullAfterSeconds: number;
}
export type SyncSnapshotV02 = Omit<Snapshot, 'protocolVersion' | 'mode'> & {
  protocolVersion: '0.2';
  mode: 'sync';
  syncCursor: OpaqueId;
  parentRevisions: AuthoritativeParentRevision[];
};
export type SyncSessionRequestV02 =
  | (Omit<SyncCollectionSessionRequest, 'protocolVersion'> & { protocolVersion: '0.2' })
  | (Omit<SyncInstanceSessionRequest, 'protocolVersion'> & { protocolVersion: '0.2' });
export type SyncSessionResultV02 =
  | (Omit<SyncCollectionSessionResult, 'acceptedProtocolVersion'> & { acceptedProtocolVersion: '0.2' })
  | (Omit<SyncInstanceSessionResult, 'acceptedProtocolVersion'> & { acceptedProtocolVersion: '0.2' });

export interface SyncPushResult {
  batchId: OpaqueId;
  results: OperationResult[];
  serverCursor: OpaqueId;
}
export interface SyncSnapshotQuery {
  sessionId: OpaqueId;
  pageCursor?: OpaqueId;
  limit?: number;
}
