/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
export default {
  plugins: ['@stryker-mutator/vitest-runner'],
  ignorePatterns: ['reports/**'],
  mutate: [
    'src/security/effective-scopes.ts',
    'src/security/credential-restrictions.ts',
    'src/security/https-enforcement.ts',
    'src/security/origin-guard.ts',
    'src/security/request-boundary.ts',
    'src/security/rate-limit.ts',
    'src/security/oauth-profile.ts',
    'src/security/sender-constraint.ts',
    'src/security/mcp-oauth-client.ts',
    'src/security/mcp-oauth-discovery.ts',
  ],
  testFiles: [
    'tests/security/**/*.test.ts',
    'tests/property/core-state-properties.test.ts',
    'tests/integration/reference-host-guard-composition.test.ts',
  ],
  testRunner: 'vitest',
  coverageAnalysis: 'perTest',
  reporters: ['clear-text', 'progress', 'html', 'json'],
  thresholds: { high: 80, low: 65, break: 65 },
  concurrency: '100%',
  timeoutFactor: 2,
  timeoutMS: 10_000,
  dryRunTimeoutMinutes: 5,
  incremental: true,
  incrementalFile: 'reports/stryker-security-incremental.json',
  htmlReporter: { fileName: 'reports/mutation/security/index.html' },
  jsonReporter: { fileName: 'reports/mutation/security/mutation.json' },
  vitest: { configFile: 'vitest.mutation.config.ts' },
};
