import { isProxy } from 'node:util/types';

import LinkHeader from 'http-link-header';

import { hasWellFormedUtf16 } from '../shared/utf16.js';
import type { Snapshot } from '../types/index.js';
import { createPublicationJsonResponse } from './publication-http-utf8.js';
import { preparePublicationSnapshotWire as prepareSnapshot } from './publication-snapshot-wire.js';
import type {
  PublicationPublicProjectionLimits,
  PublicationPublicWireOptions,
} from './publication-public-projection.js';

export type PublicationSnapshotNextLinkHeadersInit = ConstructorParameters<typeof Headers>[0];
export type PublicationSnapshotHeadersInit = PublicationSnapshotNextLinkHeadersInit;

export interface PublicationSnapshotPageResponseInit {
  readonly method: 'GET' | 'HEAD';
  /** Visibility context for the response builder; anonymous is the safe default. */
  readonly access?: 'anonymous-public' | 'authorized-private';
  readonly status?: number;
  readonly headers?: PublicationSnapshotNextLinkHeadersInit;
  /** Exact HTTP(S) URL reference generated by the server. */
  readonly nextUrl?: string | null;
  /** Exact audited public namespaces. Defaults to [] (fail-closed). */
  readonly publicExtensionNamespaces?: readonly string[];
  /** Optional public-projection depth/node budgets for the success body. */
  readonly publicProjectionLimits?: PublicationPublicProjectionLimits;
}

export type PublicationSnapshotResponseInit = PublicationSnapshotPageResponseInit;

const INVALID_NEXT_URL = 'Publication Snapshot next URL is invalid.';
const NEXT_URL_LIMIT = 'Publication Snapshot next URL limit exceeded.';
const INVALID_HEADERS = 'Publication Snapshot response headers are invalid.';
const INVALID_INIT = 'Publication Snapshot response options are invalid.';
const MAX_LINK_TARGET_LENGTH = 16 * 1_024;
const MAX_LINK_HEADER_LENGTH = 64 * 1_024;
const MAX_QUERY_LENGTH = 16 * 1_024;
const MAX_QUERY_FIELDS = 128;
const MAX_HEADER_COUNT = 128;
const CONTROL_PATTERN = /[\u0000-\u0020\u007f-\u009f]/u;
const MALFORMED_PERCENT = /%(?![0-9A-Fa-f]{2})/u;
const HEADER_NAME = /^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/u;
const URI_REFERENCE_PATTERN = /^[A-Za-z0-9\-._~:/?#\[\]@!$&'()*+,;=%]*$/u;
const URI_SCHEME_PATTERN = /^([A-Za-z][A-Za-z0-9+.-]*):/u;
const FORBIDDEN_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

class NextUrlLimitError extends Error {}

/**
 * Returns the sole RFC 8288 next Link for a validated Publication Snapshot
 * page. The target is preserved byte-for-byte from the explicit server input.
 */
export function createPublicationSnapshotNextLinkHeader(
  snapshot: unknown,
  serverNextUrl?: string | null,
): string | undefined {
  const prepared = prepareSnapshot(snapshot);
  const target = prepareNextTarget(prepared, serverNextUrl);
  return target === undefined ? undefined : formatNextLink(target);
}

/** Copy adapter headers and merge the validated Snapshot continuation Link. */
export function mergePublicationSnapshotNextLinkHeaders(
  snapshot: unknown,
  serverNextUrl?: string | null,
  headers?: PublicationSnapshotNextLinkHeadersInit,
): Headers {
  const prepared = prepareSnapshot(snapshot);
  const target = prepareNextTarget(prepared, serverNextUrl);
  const result = copyHeaders(headers);
  mergeNextLink(result, target);
  return result;
}

/**
 * Creates an adapter-ready Snapshot GET/HEAD response. Only successful page
 * responses may carry rel=next; error responses retain unrelated Links while
 * removing any stale success continuation.
 *
 * Successful publication page bodies are always public-projected before wire
 * emission (publicExtensionNamespaces defaults to [], fail-closed).
 * A supplied contentDigest is recomputed over the final public representation.
 */
export function createPublicationSnapshotPageResponse(
  value: unknown,
  init: PublicationSnapshotPageResponseInit,
): Response {
  const options = inspectResponseInit(init);
  const headers = copyHeaders(options.headers);
  const success = options.status === 200 || options.status === 304;
  let bodyValue = value;

  if (success) {
    const prepared = prepareSnapshot(value, options.projection, options.access);
    bodyValue = prepared;
    const target = prepareNextTarget(prepared, options.nextUrl);
    mergeNextLink(headers, target);
  } else {
    removeNextLinks(headers);
  }

  if (options.status === 204 || options.status === 205 || options.status === 304) {
    return new Response(null, { status: options.status, headers });
  }
  const response = createPublicationJsonResponse(bodyValue, { status: options.status, headers });
  if (options.method === 'GET') return response;
  return new Response(null, {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers,
  });
}

export const applyPublicationSnapshotNextLinkHeaders = mergePublicationSnapshotNextLinkHeaders;
export const createPublicationSnapshotResponse = createPublicationSnapshotPageResponse;

function prepareNextTarget(
  snapshot: Readonly<Snapshot>,
  value: string | null | undefined,
): string | undefined {
  try {
    if (!snapshot.page.hasMore) {
      if (value !== undefined && value !== null) throw new TypeError();
      return undefined;
    }
    if (typeof value !== 'string' || value.length === 0 || !hasWellFormedUtf16(value)) throw new TypeError();
    if (value.length > MAX_LINK_TARGET_LENGTH) throw new NextUrlLimitError();
    if (
      CONTROL_PATTERN.test(value)
      || MALFORMED_PERCENT.test(value)
      || /[<>"\\]/u.test(value)
      || !URI_REFERENCE_PATTERN.test(value)
    ) throw new TypeError();

    const scheme = URI_SCHEME_PATTERN.exec(value)?.[1]?.toLowerCase();
    if (scheme !== undefined && scheme !== 'https' && scheme !== 'http') throw new TypeError();
    if (scheme !== undefined && !/^https?:\/\/[^/?#]+/iu.test(value)) throw new TypeError();
    if (value.startsWith('//') && !/^\/\/[^/?#]+/u.test(value)) throw new TypeError();

    const url = new URL(value, 'https://publication.invalid/');
    if (
      (url.protocol !== 'https:' && url.protocol !== 'http:')
      || url.username !== ''
      || url.password !== ''
      || url.hash !== ''
      || url.hostname.length === 0
    ) throw new TypeError();
    if (url.protocol === 'http:' && !['localhost', '127.0.0.1', '[::1]'].includes(url.hostname.toLowerCase())) {
      throw new TypeError();
    }
    const queryStart = value.indexOf('?');
    const queryLength = queryStart < 0 ? 0 : value.length - queryStart - 1;
    if (queryLength > MAX_QUERY_LENGTH) throw new NextUrlLimitError();
    let fields = 0;
    for (const _entry of url.searchParams) {
      fields += 1;
      if (fields > MAX_QUERY_FIELDS) throw new NextUrlLimitError();
    }
    const cursors = url.searchParams.getAll('pageCursor');
    if (cursors.length !== 1 || cursors[0] !== snapshot.page.nextCursor) throw new TypeError();
    return value;
  } catch (error) {
    if (error instanceof NextUrlLimitError) throw new RangeError(NEXT_URL_LIMIT);
    throw new TypeError(INVALID_NEXT_URL);
  }
}

function mergeNextLink(headers: Headers, target: string | undefined): void {
  const existing = headers.get('link');
  const references = inspectExistingLinks(existing);
  const next = references.filter((reference) => relationIncludes(reference.rel, 'next'));
  if (target === undefined) {
    if (next.length > 0) throw new TypeError(INVALID_HEADERS);
    return;
  }
  if (next.length > 0) {
    if (next.length === 1 && isExactNextReference(next[0]!, target)) return;
    throw new TypeError(INVALID_HEADERS);
  }
  const addition = formatNextLink(target);
  const combined = existing === null ? addition : `${existing}, ${addition}`;
  if (combined.length > MAX_LINK_HEADER_LENGTH) throw new RangeError(INVALID_HEADERS);
  headers.set('link', combined);
}

function removeNextLinks(headers: Headers): void {
  const existing = headers.get('link');
  if (existing === null) return;
  const retained = inspectExistingLinks(existing).filter((reference) => !relationIncludes(reference.rel, 'next'));
  if (retained.length === 0) {
    headers.delete('link');
    return;
  }
  const normalized = new LinkHeader();
  for (const reference of retained) normalized.setUnique(reference);
  headers.set('link', normalized.toString());
}

function inspectExistingLinks(value: string | null): readonly LinkHeader.Reference[] {
  if (value === null) return [];
  try {
    if (value.length === 0 || value.length > MAX_LINK_HEADER_LENGTH || /[\r\n]/u.test(value)) throw new TypeError();
    const references = LinkHeader.parse(value).refs;
    if (references.length === 0) throw new TypeError();
    for (const reference of references) {
      if (typeof reference.uri !== 'string' || !safeExistingTarget(reference.uri)) throw new TypeError();
      if (typeof reference.rel !== 'string' || reference.rel.trim().length === 0) throw new TypeError();
    }
    return references;
  } catch {
    throw new TypeError(INVALID_HEADERS);
  }
}

function safeExistingTarget(value: string): boolean {
  if (
    value.length === 0
    || value.length > MAX_LINK_TARGET_LENGTH
    || CONTROL_PATTERN.test(value)
    || MALFORMED_PERCENT.test(value)
    || /[<>"\\]/u.test(value)
    || !hasWellFormedUtf16(value)
  ) return false;
  try {
    const parsed = new URL(value, 'https://publication.invalid/');
    return (parsed.protocol === 'http:' || parsed.protocol === 'https:')
      && parsed.username === ''
      && parsed.password === '';
  } catch {
    return false;
  }
}

function relationIncludes(value: string, relation: string): boolean {
  return value.trim().split(/\s+/u).some((item) => item.toLowerCase() === relation);
}

function isExactNextReference(reference: LinkHeader.Reference, target: string): boolean {
  return reference.uri === target
    && reference.rel.toLowerCase() === 'next'
    && Object.keys(reference).length === 2;
}

function formatNextLink(target: string): string {
  return `<${target}>; rel="next"`;
}

function copyHeaders(source: PublicationSnapshotNextLinkHeadersInit | undefined): Headers {
  if (source === undefined) return new Headers();
  try {
    if (isProxy(source)) throw new TypeError();
    let entries: readonly (readonly [string, string])[];
    if (source instanceof Headers) {
      entries = [...Headers.prototype.entries.call(source)];
      if (entries.length > MAX_HEADER_COUNT) throw new TypeError();
    } else if (Array.isArray(source)) {
      entries = inspectHeaderTuples(source);
    } else {
      if (typeof source !== 'object' || source === null
        || (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null)) throw new TypeError();
      const keys = Reflect.ownKeys(source);
      if (keys.length > MAX_HEADER_COUNT) throw new TypeError();
      entries = keys.map((key) => {
        if (typeof key !== 'string' || FORBIDDEN_KEYS.has(key)) throw new TypeError();
        const descriptor = Object.getOwnPropertyDescriptor(source, key);
        if (descriptor === undefined || !descriptor.enumerable || !('value' in descriptor)
          || typeof descriptor.value !== 'string') throw new TypeError();
        return [key, descriptor.value] as const;
      });
    }
    for (const [name, value] of entries) {
      if (!HEADER_NAME.test(name) || /[\r\n]/u.test(value)) throw new TypeError();
    }
    return new Headers(entries as [string, string][]);
  } catch {
    throw new TypeError(INVALID_HEADERS);
  }
}

function inspectHeaderTuples(source: readonly unknown[]): readonly (readonly [string, string])[] {
  if (source.length > MAX_HEADER_COUNT) throw new TypeError();
  return source.map((entry) => {
    if (isProxy(entry) || !Array.isArray(entry) || entry.length !== 2) throw new TypeError();
    const first = Object.getOwnPropertyDescriptor(entry, '0');
    const second = Object.getOwnPropertyDescriptor(entry, '1');
    if (first === undefined || second === undefined || !('value' in first) || !('value' in second)
      || typeof first.value !== 'string' || typeof second.value !== 'string') throw new TypeError();
    return [first.value, second.value] as const;
  });
}

function inspectResponseInit(init: PublicationSnapshotPageResponseInit): {
  readonly method: 'GET' | 'HEAD';
  readonly access: 'anonymous-public' | 'authorized-private';
  readonly status: number;
  readonly headers?: PublicationSnapshotNextLinkHeadersInit;
  readonly nextUrl?: string | null;
  readonly projection?: PublicationPublicWireOptions;
} {
  try {
    if (isProxy(init) || typeof init !== 'object' || init === null || Array.isArray(init)
      || (Object.getPrototypeOf(init) !== Object.prototype && Object.getPrototypeOf(init) !== null)) throw new TypeError();
    const keys = Reflect.ownKeys(init);
    const allowedInitKeys = new Set([
      'method', 'access', 'status', 'headers', 'nextUrl', 'publicExtensionNamespaces', 'publicProjectionLimits',
    ]);
    if (keys.some((key) => typeof key !== 'string' || !allowedInitKeys.has(key))) throw new TypeError();
    const method = ownDataValue(init, 'method');
    const access = keys.includes('access') ? ownDataValue(init, 'access') : 'anonymous-public';
    const status = keys.includes('status') ? ownDataValue(init, 'status') : 200;
    const headers = keys.includes('headers') ? ownDataValue(init, 'headers') : undefined;
    const nextUrl = keys.includes('nextUrl') ? ownDataValue(init, 'nextUrl') : undefined;
    const publicExtensionNamespaces = keys.includes('publicExtensionNamespaces')
      ? ownDataValue(init, 'publicExtensionNamespaces') : undefined;
    const publicProjectionLimits = keys.includes('publicProjectionLimits')
      ? ownDataValue(init, 'publicProjectionLimits') : undefined;
    if ((method !== 'GET' && method !== 'HEAD')
      || (access !== 'anonymous-public' && access !== 'authorized-private')
      || !Number.isInteger(status)
      || (status as number) < 200 || (status as number) > 599
      || (nextUrl !== undefined && nextUrl !== null && typeof nextUrl !== 'string')) throw new TypeError();
    let projection: PublicationPublicWireOptions | undefined;
    if (publicExtensionNamespaces !== undefined || publicProjectionLimits !== undefined) {
      projection = {
        ...(publicExtensionNamespaces === undefined
          ? {} : { publicExtensionNamespaces: publicExtensionNamespaces as readonly string[] }),
        ...(publicProjectionLimits === undefined
          ? {} : { limits: publicProjectionLimits as PublicationPublicProjectionLimits }),
      };
    }
    return {
      method, status: status as number,
      access: access as 'anonymous-public' | 'authorized-private',
      ...(headers === undefined ? {} : { headers: headers as PublicationSnapshotNextLinkHeadersInit }),
      ...(nextUrl === undefined ? {} : { nextUrl: nextUrl as string | null }),
      ...(projection === undefined ? {} : { projection }),
    };
  } catch {
    throw new TypeError(INVALID_INIT);
  }
}

function ownDataValue(source: object, key: string): unknown {
  const descriptor = Object.getOwnPropertyDescriptor(source, key);
  if (descriptor === undefined || !descriptor.enumerable || !('value' in descriptor)) throw new TypeError();
  return descriptor.value;
}
