/**
 * Public Product API surface for the web application.
 */
export {
  ProductApiError,
  isProductApiError,
  productClient,
  recoveryStrategyFor,
  getExploreCollections,
} from './productClient'
export type { RecoveryStrategy } from './productClient'
export type {
  AnnotationFormat,
  AnnotationMergePatch,
  AnnotationPage,
  AnnotationSubject,
  AnnotationType,
  AnnotationView,
  AnnotationVisibility,
  CollectionKind,
  ExploreCollection,
  ExplorePage,
  OwnedCollectionListItem,
  OwnedCollectionPage,
  OwnedCollectionPageState,
  CreateAnnotationRequest,
  CollectionVisibility,
  EditableNodeView,
  DeleteAnnotationResult,
  EditorSnapshot,
  FolderNodeView,
  MeView,
  RootNodeView,
  PublicCollectionPage,
  PublicCollectionNode,
  PublicCollectionSnapshot,
  PublicProfileCollectionSummary,
  PublicProfilePage,
  PublicProfilePageState,
  PublicProfileView,
  ProfileSummary,
  FollowRelation,
  CollectionFollowState,
  CommunityComment,
  CommunityCommentPage,
  CommunityCreateComment,
  CommunityPublicActor,
  CommunityRankingItem,
  CommunityRankingPage,
  CommunityTarget,
  CommunityTargetKind,
  CommunityTargetView,
  CommunityVoteRequest,
  CommunityVoteState,
  FollowedCollectionItem,
  FollowedCollectionPage,
  LibraryOrderSection,
  LibraryOrderSectionView,
  LibraryOrderUpdateRequest,
  LibraryOrderView,
  FollowPage,
  FeedProfileSummary,
  FeedItem,
  FeedPage,
  NotificationItem,
  NotificationInboxPage,
  NotificationReadResult,
  NotificationBulkReadResult,
  NotificationPreference,
  NotificationPreferenceEmailStatus,
  NotificationPreferenceUpdate,
  NotificationPreferenceUpdateResult,
  CreateRelationRequest,
  DeleteRelationResult,
  RelationDirection,
  RelationMergePatch,
  RelationPage,
  RelationType,
  RelationView,
  RelationVisibility,
  ReadingProgressMutationResult,
  ReadingProgressPage,
  ReadingProgressResourceType,
  ReadingProgressStatus,
  ReadingProgressUpdate,
  ReadingProgressView,
  SavedResourcePage,
  SavedResourceType,
  SavedResourceView,
  SaveResourceResult,
  WriteApprovalDecision,
  WriteApprovalDecisionRequest,
  WriteApprovalDecisionResult,
  WriteApprovalDecisionState,
  WriteApprovalImpact,
  WriteApprovalNodeSummary,
  WriteApprovalOperationPreview,
  WriteApprovalPage,
  WriteApprovalStatus,
  WriteApprovalTarget,
  WriteApprovalView,
  LinkHealthChecksReceipt,
  LinkHealthChecksRequest,
  LinkHealthItem,
  LinkHealthPage,
  LinkHealthStatus,
  ClassifyInboxAcceptReceipt,
  ClassifyInboxAcceptRequest,
  ClassifyInboxDecisionReceipt,
  ClassifyInboxItem,
  ClassifyInboxPage,
  ClassifyInboxSkipRequest,
  ClassifyInboxSuggestion,
  ClassifyInboxSuggestionKind,
  ExportJob,
  ExportJobPage,
  ExportJobStatus,
  ExportLibraryDocument,
  OrganizePlan,
  OrganizePlanAction,
  OrganizePlanApplyReceipt,
  OrganizePlanApplyRequest,
  OrganizePlanCreateRequest,
  CollectionVersion,
  CollectionVersionCreateRequest,
  CollectionVersionPage,
  CollectionVersionRestoreReceipt,
  CollectionVersionRestoreRequest,
  PublicReportIssue,
  PublicReportIssuePage,
  PublicReportPage,
  PublicReportSeries,
  ReportFollowState,
  ReportIssueTimelineItem,
  ReportIssueTimelinePage,
  ReportSeries,
  ReportSeriesCreate,
  ReportSeriesPage,
  ReportSeriesPatch,
  ReportEdition,
  ReportEditionAttach,
  ReportEditionPatch,
  ReportMember,
  ReportMemberMutation,
  ReportSchedule,
  ReportScheduleInput,
  SearchPage,
  SearchPageState,
  SearchResourceType,
  SearchResult,
  SyncReplicaStatus,
  SyncDeviceView,
  SyncReplicaView,
  SyncStatusView,
  SyncConflictSafeSummary,
  SyncConflictSummary,
  SyncConflictPage,
  ProductSyncConflictResolution,
  ProductSyncConflictResolutionView,
  ProductSyncReplicaRetirementView,
  SyncTrashDeletionId,
  SyncTrashListItem,
  SyncTrashPage,
  SyncTrashDetail,
  SyncTrashRestoreView,
  SyncTrashRestoreBatchItem,
  SyncTrashRestoreBatchRequest,
  SyncTrashRestoreItemResult,
  SyncTrashRestoreBatchSummary,
  SyncTrashRestoreBatchView,
  SyncTrashEmptyRequest,
  SyncTrashEmptySkipReason,
  SyncTrashEmptyItemResult,
  SyncTrashEmptySummary,
  SyncTrashEmptyView,
  CreditOverview,
  CreditLedgerEntry,
  CreditLedgerPage,
  CreditUsage,
  CreditBillingConsent,
} from './types'
export type { CreditLedgerListParams } from './product-transport-types'
export type { CommunityCommentRepliesQueryParams, CommunityCommentsQueryParams, CommunityNotificationsQueryParams, CommunityRankingQueryParams, CommunityTargetQuery } from './productClient'
export type { SessionSnapshot } from './sessionStore'
// Session identity/subscription are read-only primitives the library desk needs
// to scope cached snapshots to the signed-in account. Re-export them here so
// consumers never deep-import the session store module.
export { privateSessionIdentity, subscribeSession } from './sessionStore'

// Mock data lives in `./mock-data` and is only reached through dynamic
// imports on flag-off paths, so the live entry never carries the demo seed.

// Feature flags.
export { FEATURE_FLAGS, isLive, isFollowExposureEnabled, isCollectionFollowExposureEnabled, isFeedExposureEnabled, isNotificationExposureEnabled, isWriteApprovalsExposureEnabled, isLinkHealthExposureEnabled, isClassifyInboxExposureEnabled, isClassificationExposureEnabled, isClassificationBatchExposureEnabled, isAiOrganizeExposureEnabled, isCollectionHistoryExposureEnabled, isExportJobsExposureEnabled, isEmailNotificationsExposureEnabled, isReadableReplicaExposureEnabled, isReportsExposureEnabled, isCommunityExposureEnabled, mockOrLive } from './featureFlags'
export type { FeatureFlag } from './featureFlags'

export type {
  BookmarkFaviconSource,
  CollectionChildrenItem,
  CollectionChildrenPage,
  CollectionChildrenItemKind,
  CollectionChildrenSort,
  FaviconCreateIconJobRequest,
  FaviconIconJob,
  FaviconIconPolicy,
  FaviconIconPolicyPatch,
  FaviconPolicyResult,
  FaviconJobStatus,
  SetBookmarkFaviconSourceRequest,
} from './types'

export type { ClassificationProviderProfile, ClassificationSettingsV2, ClassificationSettingsPatchV2, ClassificationRun, ClassificationRunCreateRequest, ClassificationRunApplyRequest, ClassificationRunApplyResponse, ClassificationPreviewRequest, ClassificationPreviewResponse, ClassificationSettings, ClassificationSettingsPatch, ClassificationConfirmationRequest, ClassificationConfirmationResponse } from '@known/product-v1-client'
