import { createRequire } from 'node:module';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const outputPath = resolve(packageRoot, 'src/version.ts');

const serverPackage = readJson(resolve(packageRoot, 'package.json'));
const colpPackage = readJson(packageJsonAbove(require.resolve('@know-n/colp')));
const schema = await import('@know-n/colp/schema');

const server = versionString(serverPackage.version, '@know-n/colp-server');
const colp = versionString(colpPackage.version, '@know-n/colp');
const protocols = protocolVersions(schema.collectionProtocolSchemas);

const source = [
  '// Generated by scripts/write-version.mjs. Do not edit.',
  'export const version = {',
  `  server: '${server}',`,
  `  colp: '${colp}',`,
  `  protocols: [${protocols.map((item) => `'${item}'`).join(', ')}],`,
  '} as const;',
  '',
].join('\n');

writeFileSync(outputPath, source);

function packageJsonAbove(entry) {
  let directory = dirname(entry);
  while (true) {
    const candidate = resolve(directory, 'package.json');
    if (existsSync(candidate)) return candidate;
    const parent = dirname(directory);
    if (parent === directory) throw new Error(`package.json not found above ${entry}`);
    directory = parent;
  }
}

function readJson(path) {
  const parsed = JSON.parse(readFileSync(path, 'utf8'));
  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error(`${path} is not a JSON object`);
  }
  return parsed;
}

function versionString(value, label) {
  if (typeof value !== 'string' || !/^[0-9A-Za-z.+-]+$/.test(value)) {
    throw new Error(`${label} version is missing or not a single token`);
  }
  return value;
}

function protocolVersions(schemas) {
  if (typeof schemas !== 'object' || schemas === null) {
    throw new Error('@know-n/colp does not declare collectionProtocolSchemas');
  }
  const versions = Object.keys(schemas);
  if (versions.length === 0 || versions.some((item) => !/^[0-9]+(?:\.[0-9]+)+$/.test(item))) {
    throw new Error('@know-n/colp protocol versions are missing or not dotted numbers');
  }
  return versions;
}
