/**
 * G03 contract tests for the dead-class ratchet.
 * Run with: node --test scripts/dead-classes-contract.test.mjs
 */
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

import { classesByFile, findDeadClasses, findGhostClasses, isUsed, usageCorpus } from './check-dead-classes.mjs'

const here = fileURLToPath(new URL('.', import.meta.url))
const webRoot = join(here, '..')

test('real tree unreferenced classes stay within the recorded baseline', () => {
  // R9-29: the tightened criterion surfaced real pre-existing dead classes
  // (masked before by comment/test-file evidence). They are recorded in
  // dead-classes-baseline.json as shrink-only debt — removal shrinks the
  // baseline, any NEW dead class still fails here and in the CLI gate.
  const dead = Object.fromEntries(findDeadClasses(webRoot))
  const baseline = JSON.parse(readFileSync(join(webRoot, 'scripts', 'dead-classes-baseline.json'), 'utf8'))
  const deadSet = new Set(Object.entries(dead).flatMap(([f, ns]) => ns.map((n) => `${f}::${n}`)))
  const baselineSet = new Set(Object.entries(baseline).flatMap(([f, ns]) => ns.map((n) => `${f}::${n}`)))
  const newDead = [...deadSet].filter((k) => !baselineSet.has(k))
  assert.deepEqual(newDead, [], `new dead classes not in baseline: ${newDead.join(', ')}`)
})

test('real tree renders no ghost classes (JSX tokens without a stylesheet or hook)', () => {
  const ghosts = Object.fromEntries(findGhostClasses(webRoot))
  assert.deepEqual(ghosts, {}, `ghost classes found: ${JSON.stringify(ghosts, null, 2)}`)
})

test('ghost detector ignores styled, hooked and interpolated tokens', () => {
  const dir = mkdtempSync(join(tmpdir(), 'ghost-classes-'))
  try {
    mkdirSync(join(dir, 'src', 'styles'), { recursive: true })
    mkdirSync(join(dir, 'e2e'), { recursive: true })
    writeFileSync(join(dir, 'src', 'styles', 'x.css'), '.styled { color: red; }\n.styled-child { color: red; }\n')
    writeFileSync(
      join(dir, 'src', 'App.tsx'),
      [
        'export function App({ kind }: { kind: string }) {',
        '  return (',
        '    <div className="styled ghost-static">',
        '      <span className={`tone-${kind} ghost-template`} />',
        "      <i className={'hooked-by-test'} />",
        '      <b className="hooked-by-e2e" />',
        '    </div>',
        '  )',
        '}',
      ].join('\n'),
    )
    writeFileSync(join(dir, 'src', 'App.test.tsx'), "document.querySelector('.hooked-by-test')\n")
    writeFileSync(join(dir, 'e2e', 'app.spec.ts'), "page.locator('.hooked-by-e2e')\n")
    const ghosts = Object.fromEntries(findGhostClasses(dir))
    assert.deepEqual(ghosts, { 'ghost-static': ['src/App.tsx'], 'ghost-template': ['src/App.tsx'] })
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('detector finds an orphaned class and respects whole-word matching', () => {
  const dir = mkdtempSync(join(tmpdir(), 'dead-classes-'))
  try {
    mkdirSync(join(dir, 'src', 'styles'), { recursive: true })
    writeFileSync(join(dir, 'src', 'styles', 'x.css'), '.used-thing { color: red; }\n.orphan-thing { color: red; }\n.muted { color: gray; }\n')
    mkdirSync(join(dir, 'src'), { recursive: true })
    writeFileSync(join(dir, 'src', 'App.tsx'), 'export function App() { return <div className="used-thing muted-x">x</div> }\n')
    const dead = findDeadClasses(dir)
    // .muted must not match the .muted-x class usage (whole-word only)
    assert.deepEqual([...dead.get('x.css')], ['muted', 'orphan-thing'])
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('dynamic template prefixes keep generated classes alive', () => {
  const corpus = { text: 'const c = `tile-${type}`', dynamicPrefixes: new Set(['tile-']) }
  assert.equal(isUsed('tile-github', corpus), true)
  // the bare stem is not generated by the template — it needs a literal usage
  assert.equal(isUsed('tile', corpus), false)
  assert.equal(isUsed('tiles', corpus), false)
})

test('short is-${} stems do not keep unrelated is-* classes alive', () => {
  const corpus = { text: 'const c = `is-${type}`', dynamicPrefixes: new Set(['is-']) }
  assert.equal(isUsed('is-orphan', corpus), false)
  assert.equal(isUsed('is-active', corpus), false)
})

test('class extraction reads grouped and nested selectors', () => {
  const dir = mkdtempSync(join(tmpdir(), 'dead-classes-extract-'))
  try {
    mkdirSync(join(dir, 'src', 'styles'), { recursive: true })
    writeFileSync(
      join(dir, 'src', 'styles', 'x.css'),
      '@layer pages {\n.a, .b:hover { color: red; }\n@media (max-width: 639px) {\n.c { color: blue; }\n}\n}\n',
    )
    const map = classesByFile(join(dir, 'src', 'styles'))
    assert.deepEqual([...map.get('x.css')].sort(), ['a', 'b', 'c'])
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('usage corpus covers production sources', () => {
  const corpus = usageCorpus(webRoot)
  assert.ok(corpus.text.length > 1000, 'corpus should be non-trivial')
})

test('test files and comments do not count as usage (R9-29)', () => {
  const dir = mkdtempSync(join(tmpdir(), 'dead-classes-'))
  try {
    mkdirSync(join(dir, 'src', 'styles'), { recursive: true })
    mkdirSync(join(dir, 'e2e'), { recursive: true })
    writeFileSync(
      join(dir, 'src', 'styles', 'x.css'),
      '.prod-used { color: red; }\n.test-only { color: red; }\n.comment-only { color: red; }\n',
    )
    writeFileSync(
      join(dir, 'src', 'App.tsx'),
      'export function App() { return <div className="prod-used">x</div> } // .comment-only lives here\n',
    )
    writeFileSync(join(dir, 'src', 'App.test.tsx'), "document.querySelector('.test-only')\n")
    writeFileSync(join(dir, 'e2e', 'app.spec.ts'), "page.locator('.test-only')\n")
    const dead = findDeadClasses(dir)
    assert.deepEqual([...dead.get('x.css')].sort(), ['comment-only', 'test-only'])
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})
