import { mkdir, mkdtemp, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { resolve } from 'node:path'
import { ICON_NAMES, ICON_STROKE_WIDTH, ICON_VIEW_BOX, SHARED_ICON_PATHS, isFilledIcon } from '../src/components/icon-paths.ts'

// Node 22.18+ (native type stripping). No server or network needed.
const directory = process.argv[2] ? resolve(process.argv[2]) : await mkdtemp(resolve(tmpdir(), 'known-icons-'))
await mkdir(directory, { recursive: true })
const svg = (name, size = 20) => `<svg data-icon="${name}" viewBox="${ICON_VIEW_BOX}" width="${size}" height="${size}" fill="none" stroke="currentColor" stroke-width="${ICON_STROKE_WIDTH}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${SHARED_ICON_PATHS[name]}" ${isFilledIcon(name) ? 'fill="currentColor" stroke="none"' : ''}/></svg>`
const toolbar = `<div class="toolbar"><span>${svg('library')} My library</span><span>${svg('search')} Search bookmarks</span><span>${svg('folder')} Reading</span><span>${svg('bookmark')} Save</span><span>${svg('sparkle')} Organize</span><span>${svg('settings')}</span></div>`
const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Know-N · Functional icons</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f5f6;color:#06070a;font:14px/1.5 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:48px}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:28px}h1{font-size:34px;letter-spacing:-1.4px;margin:4px 0;font-weight:550}p{margin:0;color:#616367}.eyebrow{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#386695}.spec{max-width:300px;text-align:right;font-size:12px}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:18px 24px;border:1px solid #06070a15;border-radius:12px;background:#fff}.toolbar span{display:inline-flex;align-items:center;gap:8px}.ink{margin-top:10px;color:#ecf3fa;background:#1c2026;border-color:#ffffff18}.ink span:first-child{color:#a7c8e7}h2{font-size:13px;letter-spacing:.2px;font-weight:550;margin:30px 0 12px}.grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:1px;background:#06070a10;border:1px solid #06070a10;border-radius:12px;overflow:hidden}.glyph{background:#fdfefe;padding:16px 12px 12px;min-width:0}.sizes{display:flex;align-items:center;justify-content:space-around;height:36px;gap:10px;color:#33353a}.glyph p{font:11px/1.5 ui-monospace,monospace;margin-top:12px;text-align:center}.sizes svg{flex-shrink:0}footer{display:flex;justify-content:space-between;padding-top:20px;color:#616367;font-size:12px}@media(max-width:850px){main{padding:24px}.grid{grid-template-columns:repeat(3,minmax(0,1fr))}.toolbar{flex-wrap:wrap}header{display:block}.spec{text-align:left;margin-top:12px}}
</style><main><header><div><p class="eyebrow">Know-N · Interface essentials</p><h1>A quieter, coherent icon family.</h1><p>Rounded geometry. Open counters. A shared visual rhythm.</p></div><p class="spec">24-unit grid / 1.5-unit stroke<br>16 · 20 · 24 · 32 px optical review<br>Same paths in web and extension</p></header>${toolbar}${toolbar.replace('class="toolbar"', 'class="toolbar ink"')}<h2>${ICON_NAMES.length - 1} functional glyphs · 1 preserved provider mark</h2><div class="grid">${ICON_NAMES.map(name => `<div class="glyph"><div class="sizes">${[16, 20, 24, 32].map(size => svg(name, size)).join('')}</div><p>${name}</p></div>`).join('')}</div><footer><span>CurrentColor · Decorative SVGs · Shared state geometry</span><span>Brandmark and favicon unchanged</span></footer></main></html>`
const output = resolve(directory, 'index.html')
await writeFile(output, html)
console.log(output)
