import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import ts from 'typescript';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');
const schemaPath = resolve(
  packageRoot,
  'src',
  'schema',
  'generated',
  'collection-protocol.schema.json',
);
const outputPath = resolve(packageRoot, 'src', 'types', 'generated.ts');
const schema = JSON.parse(await readFile(schemaPath, 'utf8'));
const schemaV02Path = resolve(
  packageRoot,
  'src',
  'schema',
  'generated',
  'collection-protocol-0.2.schema.json',
);
const schemaV02 = JSON.parse(await readFile(schemaV02Path, 'utf8'));
// tsup's declaration JSON plugin emits executable initializers into .d.ts.
// Native generated TypeScript keeps the same inferred public schema types and
// lets the compiler emit valid ambient declarations without that JSON plugin.
for (const [version, document] of [['0.1', schema], ['0.2', schemaV02]]) {
  const modulePath = resolve(packageRoot, 'src/schema/generated', `v${version}`, 'generated.ts');
  const moduleSource = [
    '/** Generated from the protocol JSON Schema; run npm run generate:types. */',
    'const schema = ' + JSON.stringify(document, null, 2).replace(/^(\s*)"__proto__":/gmu, '$1["__proto__"]:') + ';',
    'export default schema;',
    '',
  ].join('\n');
  if (checkOnly) {
    if (await readFile(modulePath, 'utf8') !== moduleSource) {
      throw new Error(`Generated Schema module ${version} is stale. Run npm run generate:types.`);
    }
  } else {
    await mkdir(dirname(modulePath), { recursive: true });
    await writeFile(modulePath, moduleSource, 'utf8');
  }
}
for (const requiredDefinition of [
  'manifestV02',
  'authoritativeEffectPage',
  'authoritativePullEffect',
  'syncPullEventV02',
  'syncPullV02',
  'syncSnapshotV02',
  'syncSessionRequestV02',
  'syncSessionResultV02',
]) {
  if (!(requiredDefinition in schemaV02.$defs)) {
    throw new Error(`COLP 0.2 schema is missing ${requiredDefinition}.`);
  }
}
const definitionNames = Object.keys(schema.$defs).sort();

const typeIndexSchema = {
  $schema: schema.$schema,
  title: 'ColpContracts',
  type: 'object',
  additionalProperties: false,
  properties: Object.fromEntries(
    definitionNames.map((name) => [name, { $ref: `#/$defs/${name}` }]),
  ),
  required: definitionNames,
  $defs: schema.$defs,
};

const source = await compile(typeIndexSchema, 'ColpContracts', {
  bannerComment: [
    '/* eslint-disable */',
    '/**',
    ' * Generated from The Collection Protocol schema.',
    ' * Run `npm run refresh:protocol`; do not edit this file manually.',
    ' */',
  ].join('\n'),
  enableConstEnums: false,
  format: true,
  style: {
    bracketSpacing: true,
    printWidth: 100,
    semi: true,
    singleQuote: true,
    tabWidth: 2,
    trailingComma: 'all',
    useTabs: false,
  },
});

const sourceFile = ts.createSourceFile(
  outputPath,
  source,
  ts.ScriptTarget.Latest,
  false,
  ts.ScriptKind.TS,
);
const strictOverrides = new Map([
  ['FeedEvent', 'StrictFeedEvent'],
  ['FeedNode', 'StrictFeedNode'],
  ['Node', 'StrictNode'],
  ['NodeCreate', 'StrictNodeCreate'],
  ['Operation', 'StrictOperation'],
  ['OperationResult', 'StrictOperationResult'],
  ['SnapshotNode', 'StrictSnapshotNode'],
]);
const declarations = sourceFile.statements
  .filter(
    (statement) =>
      (ts.isInterfaceDeclaration(statement) || ts.isTypeAliasDeclaration(statement)) &&
      strictOverrides.has(statement.name.text),
  )
  .sort((left, right) => right.getStart(sourceFile) - left.getStart(sourceFile));
let generatedSource = source;
for (const declaration of declarations) {
  const name = declaration.name.text;
  const replacement = `export type ${name} = ${strictOverrides.get(name)};`;
  generatedSource =
    generatedSource.slice(0, declaration.getStart(sourceFile)) +
    replacement +
    generatedSource.slice(declaration.getEnd());
}
const snapshotNodeUnion = '  nodes: (Node | SnapshotNode)[];';
if (!generatedSource.includes(snapshotNodeUnion)) {
  throw new Error('Generated Snapshot Node projection was not found.');
}
// The no-index Node branch is already contained by StrictSnapshotNode's optional index projection.
generatedSource = generatedSource.replace(snapshotNodeUnion, '  nodes: SnapshotNode[];');
const firstExportOffset = generatedSource.indexOf('export ');
const strictImport = [
  "import type { StrictFeedEvent, StrictFeedNode, StrictNode, StrictNodeCreate, StrictOperation, StrictOperationResult, StrictSnapshotNode } from './strict.js';",
  '',
].join('\n');
generatedSource =
  generatedSource.slice(0, firstExportOffset) +
  strictImport +
  generatedSource.slice(firstExportOffset);
const versionedTypesPath = resolve(packageRoot, 'scripts', 'templates', 'authoritative-pull-types.ts');
const versionedTypes = await readFile(versionedTypesPath, 'utf8');
const versionedTypesMarker = 'export interface SyncPushResult {';
if (!generatedSource.includes(versionedTypesMarker)) {
  throw new Error('Generated Sync Push result declaration was not found.');
}
generatedSource = generatedSource.replace(
  versionedTypesMarker,
  `${versionedTypes.trim()}\n\n${versionedTypesMarker}`,
);
const contractMarker = '  syncPull: SyncPull;';
generatedSource = generatedSource.replace(contractMarker, [
  contractMarker,
  '  manifestV02: ManifestV02;',
  '  syncPullV02: SyncPullV02;',
  '  syncPullEventV02: SyncPullEventV02;',
  '  syncSnapshotV02: SyncSnapshotV02;',
  '  authoritativeEffectPage: AuthoritativeEffectPage;',
  '  authoritativePullEffect: AuthoritativePullEffect;',
].join('\n'));
generatedSource = generatedSource.replace(
  '  syncSessionRequest: SyncSessionRequest;',
  '  syncSessionRequest: SyncSessionRequest;\n  syncSessionRequestV02: SyncSessionRequestV02;',
);
generatedSource = generatedSource.replace(
  '  syncSessionResult: SyncSessionResult;',
  '  syncSessionResult: SyncSessionResult;\n  syncSessionResultV02: SyncSessionResultV02;',
);
// Keep the tracked generated artifact identical on Windows and Linux checkouts.
generatedSource = generatedSource.replace(/\r\n?/g, '\n');
if (checkOnly) {
  const current = await readFile(outputPath, 'utf8');
  if (current !== generatedSource) {
    throw new Error('Generated TypeScript contracts are stale. Run npm run refresh:protocol.');
  }
} else {
  await writeFile(outputPath, generatedSource, 'utf8');
}
console.log(
  `${checkOnly ? 'Checked' : 'Generated'} TypeScript contracts for ${definitionNames.length} schema definitions.`,
);
