export type {
  Account,
  AccountIdentity,
  AccountStatus,
  AccountWithProfile,
  AuthUserAccountMapping,
  IssuedSessionSecrets,
  MappedBusinessAccount,
  OidcLoginTransaction,
  Profile,
  ProfileHandle,
  Session,
  SessionExpiryWindow,
} from './types.js';
export { IdentityError, type IdentityErrorCode } from './errors.js';
export {
  OIDC_LOGIN_TRANSACTION_TTL_MS,
  SESSION_ABSOLUTE_TTL_MS,
  SESSION_IDLE_TTL_MS,
  SESSION_ROTATION_MIN_AGE_MS,
  SESSION_TOUCH_MIN_INTERVAL_MS,
  assertAccountCanIssueSession,
  assertSessionUsable,
  computeSessionExpiryWindow,
  computeSlidIdleExpiry,
  isSecurityEpochMatch,
  isSessionAbsoluteExpired,
  isSessionExpired,
  isSessionIdleExpired,
  isSessionRevoked,
  shouldRotateSession,
  shouldTouchSession,
} from './session-policy.js';
export {
  assertSafeRelativeReturnTo,
  canonicalizeSafeReturnTo,
  isSafeRelativeReturnTo,
} from './return-to.js';
export {
  deriveCsrfTokenRaw,
  deriveRotatedSessionTokenRaw,
  createSessionRotationSecrets,
  createTestSessionRotationSecrets,
  generateCsrfTokenRaw,
  generateOidcStateMaterial,
  generateOpaqueId,
  generatePkceCodeVerifier,
  generateSessionTokenRaw,
  hashSecret,
  hashesMatch,
  secretsMatch,
  type SessionRotationSecretsPort,
} from './secrets.js';
export {
  OIDC_NONCE_DIGEST_PURPOSE,
  OIDC_STATE_DIGEST_PURPOSE,
  createOidcTransactionSecrets,
  createTestOidcTransactionSecrets,
  encodeOidcEncryptionKeyBase64,
  isProtectedOidcTransaction,
  materializeOidcLoginTransactionForUse,
  parseOidcEncryptionKeysEnv,
  type OidcEncryptionKey,
  type OidcTransactionSecretsConfig,
  type OidcTransactionSecretsPort,
  type PkceEncryptionResult,
} from './oidc-transaction-crypto.js';
export {
  ABOUT_MAX,
  HANDLE_CLAIM_MAX,
  assertClaimableHandle,
  assertNonEmpty,
  assertSameOriginAvatarUrl,
  assertValidAbout,
  assertValidAvatarUrl,
  assertValidDisplayName,
  assertValidEmail,
  assertValidHandle,
  isValidAvatarUrl,
} from './validation.js';
export {
  BARE_HANDLE_ATTEMPTS,
  HANDLE_ADJECTIVES,
  HANDLE_NOUNS,
  HANDLE_WORD_MAX,
  generateAutomaticHandle,
} from './handle-generation.js';
export {
  DEFAULT_OIDC_EMAIL_TRUST_POLICY,
  NOOP_OIDC_CLAIM_SYNC_METRICS,
  OIDC_AVATAR_URL_REJECTED_METRIC,
  resolveTrustedOidcClaims,
  type OidcClaimSyncMetrics,
  type OidcEmailTrustPolicy,
  type ResolveTrustedOidcClaimsInput,
  type TrustedOidcProfileClaims,
} from './oidc-claims-policy.js';
export {
  ALLOWED_ID_TOKEN_ALGORITHMS,
  IdTokenVerificationError,
  createIdTokenVerifier,
  type AllowedIdTokenAlgorithm,
  type IdTokenVerificationFailureReason,
  type IdTokenVerifier,
  type IdTokenVerifierOptions,
  type IdTokenVerifyInput,
  type JwksProvider,
  type VerifiedIdTokenClaims,
} from './id-token-verifier.js';
